/-
Copyright (c) 2026 Gaspard Reghem. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Gaspard Reghem
-/

import Leslie2.Systems.System
import Leslie2.Other.Seq
import Mathlib.Data.Seq.Basic

/-!
# Trace core

Core trace machinery for labelled probabilistic transition systems: the
`System` structure (a `System` with an internal/external label
partition), the `trace` of an execution, trace-tightness (`IsTight`), the trace
probability `traceProb`, the set `achievableTraceDists` of achievable trace
distributions, the regrouping of `traceProb` by label list
(`traceProb_eq_labProb_sum`), and the linearity of `probOf` in the initial
distribution (`probOf_init_factor`, `probOf_init_mix`).

This is layer 1 of the weak-transition development; the weak-scheduler bind
calculus (`SchedulerBind`) and the weak transitions themselves (`WeakStep`)
build on top of it.
-/

open Stream'

namespace PLTS

variable {α β State State_C State_A Label : Type}

/-! ### Internal/external labels and weak transitions -/

/-- A label type with a distinguished **silent** (internal) label `τ`. Every
other label is *external* (observable). The internal/external partition is thus
*canonical*: it depends only on the label type, not on any individual system. -/
class Silent (Label : Type) where
  /-- The unique internal (silent) label. -/
  τ : Label

variable [Silent Label]

/-! ### Traces

A label `l` is *internal* (silent) when `l = Silent.τ`, and *external*
(observable) otherwise; the trace drops the internal (`τ`) transitions. The
classification is canonical — it depends only on the label type (via `Silent`),
not on any system. -/

/-- The trace of a (possibly infinite) execution `e` under a labelled system
`ls`: the sequence of external labels appearing in `e.trans`, in order, with
internal (τ) labels dropped. Finite if `e` has finitely many external
transitions, infinite otherwise. -/
noncomputable def System.trace (_ls : System State Label)
    (e : AlterSeq State Label) : Seq Label :=
  (e.trans.filter (fun p => ¬ (p.1 = Silent.τ))).map Prod.fst

/-- The trace of an execution with no transitions is the empty sequence. -/
@[simp] theorem System.trace_init
    (ls : System State Label) (s : State) :
    ls.trace ⟨s, (Seq.nil : Seq (Label × State))⟩ = (Seq.nil : Seq Label) := by
  simp [System.trace]

/-- The trace of an execution whose first transition has an *external* label
`l` starts with `l`, followed by the trace from the rest of the execution. -/
@[simp] theorem System.trace_cons_external
    (ls : System State Label) (s : State) (l : Label) (s' : State)
    (rest : Seq (Label × State)) (h : ¬ (l = Silent.τ)) :
    ls.trace ⟨s, Seq.cons (l, s') rest⟩ = Seq.cons l (ls.trace ⟨s', rest⟩) := by
  unfold System.trace
  rw [Seq.filter_cons_pos (l, s') rest h, Seq.map_cons]

/-- A finite execution is *trace-tight* under `ls` if either it has no
transitions, or its last transition is external. Tight executions correspond
to "trace cone boundaries": each trajectory has at most one tight prefix per
finite trace.

This rules out the artefact where a single trajectory contributes to the
trace probability *infinitely many times* via nested cylinders — a finite
prefix and any of its extensions by trailing internal transitions all have
the same trace, but only one of them (the shortest, ending right after the
last external transition or with no transitions at all) is tight. -/
def System.IsTight
    (_ls : System State Label) (e : AlterSeq State Label) : Prop :=
  e.trans.TerminatedAt 0 ∨
  ∃ (n : ℕ) (l : Label) (s : State),
    e.trans.get? n = some (l, s) ∧
    e.trans.TerminatedAt (n + 1) ∧
    ¬ (l = Silent.τ)

/-- The probability that the probabilistic execution `pe` produces the finite
trace `τ` under `ls`: the (countable) sum of `pe.probOf` over all
*trace-tight* finite executions `e` with `ls.trace e = τ`.

The tightness condition (`IsTight`) ensures the summands correspond to
disjoint cylinders in the trace cone for `τ`: a trajectory contributes
exactly once via its unique tight prefix (the shortest prefix with trace `τ`,
ending right after the last external transition). Without tightness, internal
loops would cause double-counting — see the docstring of `IsTight` for the
artefact this prevents.

For finite `τ` this is the standard trace-cone probability (i.e. the
probability that the trajectory's first `|τ|` external labels are exactly
`τ`). For infinite `τ` the sum is `0` since no finite execution has an
infinite trace; capturing infinite-trace probabilities would require moving
to a measure-theoretic setting on the σ-algebra generated by trace cones. -/
noncomputable def System.traceProb (ls : System State Label)
    (pe : ProbabilisticExecution ls) (τ : Seq Label) : ENNReal :=
  ∑' e : {e : AlterSeq State Label //
      e.trans.Terminates ∧ ls.trace e = τ ∧ ls.IsTight e},
    pe.probOf e.1 e.2.1

/-! ### Trace-distribution sets achievable by a system -/

/-- The set of trace distributions achievable by some probabilistic execution
of the labelled system `ls` **that starts at the system's initial state**, i.e.
whose initial distribution is the Dirac `PMF.pure ls.init`. Equality of this set
across two systems means the systems are trace-distribution-equivalent.

The Dirac-init requirement is essential: it restricts to executions that
correspond to genuine runs of `ls` from its designated start state. Without it
the `𝒟(sys)` lift admits mixture initial distributions over `PMF State` that no
single `sys`-execution realises, and the trace-distribution equivalence fails
(the `𝒟`-side `belief` reconstruction is unsound for mixture inits). -/
def achievableTraceDists (ls : System State Label) :
    Set (Seq Label → ENNReal) :=
  {D | ∃ pe : ProbabilisticExecution ls,
    pe.initState = PMF.pure ls.init ∧ ∀ τ, ls.traceProb pe τ = D τ}

/-! ### Regrouping `traceProb` by label list

`traceTightLabs` and `traceProb_eq_labProb_sum` depend only on the silent label
`τ` (via `trace`/`IsTight`), so they are shared by every construction over the
same label type (`𝒟(sys)`, `sys^w`). They live here so all such constructions
can reuse the regrouping. -/

open Classical in
/-- The label lists realisable by a *tight* execution with external trace `τ`:
the external (non-internal) sublist of `labs` equals `τ`, and `labs` is empty or
ends with an external label. Depends only on the silent label `τ`, so it is *identical*
for `sys` and any construction sharing `internal` (e.g. `𝒟(sys)`, `sys^w`). -/
def System.traceTightLabs {S L : Type} [Silent L] (_ls : System S L)
    (τ : Seq L) (labs : List L) : Prop :=
  ((Seq.ofList labs).filter (fun l => ¬ (l = Silent.τ)) = τ) ∧
    (∀ l, labs.getLast? = some l → ¬ (l = Silent.τ))

/-- Mapping `Prod.fst` over a `Seq.ofList` equals `Seq.ofList` of the mapped list. -/
private theorem System.map_ofList {S L : Type} (l : List (L × S)) :
    (Seq.ofList l).map Prod.fst = Seq.ofList (l.map Prod.fst) := by
  induction l with
  | nil => rw [Stream'.Seq.ofList_nil, Stream'.Seq.map_nil, List.map_nil, Stream'.Seq.ofList_nil]
  | cons a l ih =>
    rw [Stream'.Seq.ofList_cons, Stream'.Seq.map_cons, List.map_cons, Stream'.Seq.ofList_cons, ih]

/-- The trace can be expressed as first mapping `Prod.fst` then filtering by
"non-internal", swapping the order in the definition of `trace`. -/
private theorem System.trace_eq_filter_map {S L : Type} [Silent L] (ls : System S L)
    (e : AlterSeq S L) :
    ls.trace e = (e.trans.map Prod.fst).filter (fun l => ¬ (l = Silent.τ)) := by
  unfold System.trace
  rw [Stream'.Seq.filter_map Prod.fst (fun l => ¬ (l = Silent.τ))]
  rfl

open Classical in
/-- The correspondence at the heart of the reindexing: for a terminating
execution `e` with label list `labs := (e.trans.toList h).map Prod.fst`, being a
trace-`τ` tight execution is equivalent to `traceTightLabs τ labs`.

Exposed (not `private`) so downstream constructions can reuse the
tight-execution ↔ label-list correspondence. -/
theorem System.tight_iff {S L : Type} [Silent L] (ls : System S L)
    (τ : Seq L) (e : AlterSeq S L) (h : e.trans.Terminates) :
    (ls.trace e = τ ∧ ls.IsTight e)
      ↔ ls.traceTightLabs τ ((e.trans.toList h).map Prod.fst) := by
  set labs := (e.trans.toList h).map Prod.fst with hlabs
  have h_map : e.trans.map Prod.fst = Seq.ofList labs := by
    rw [hlabs, ← System.map_ofList, Stream'.Seq.ofList_toList e.trans h]
  unfold System.traceTightLabs
  -- Part 1: trace equality.
  have part1 : ls.trace e = τ ↔ (Seq.ofList labs).filter (fun l => ¬ (l = Silent.τ)) = τ := by
    rw [ls.trace_eq_filter_map e, h_map]
  -- Part 2: tightness equality.
  have part2 : ls.IsTight e ↔ (∀ l, labs.getLast? = some l → ¬ (l = Silent.τ)) := by
    unfold System.IsTight
    -- `labs.getLast? = (e.trans.get? (length - 1)).map Prod.fst`.
    have h_glast : labs.getLast? = (e.trans.get? (e.trans.length h - 1)).map Prod.fst := by
      rw [hlabs, List.getLast?_map, Stream'.Seq.getLast?_toList e.trans h]
    by_cases h0 : e.trans.TerminatedAt 0
    · -- Empty transitions: tight (left disjunct), getLast? = none, RHS vacuous.
      have h_nil : e.trans = Stream'.Seq.nil := Stream'.Seq.terminatedAt_zero_iff.mp h0
      have h_len0 : e.trans.length h = 0 :=
        Nat.le_zero.mp (Stream'.Seq.length_le_iff.mpr h0)
      have h_getlast_none : labs.getLast? = none := by
        rw [h_glast, h_len0]
        rw [show e.trans.get? (0 - 1) = none from by rw [h_nil]; rfl]
        rfl
      constructor
      · intro _ l hl; rw [h_getlast_none] at hl; exact absurd hl (by simp)
      · intro _; left; exact h0
    · -- Nonempty: length ≥ 1, left disjunct false; both sides reduce to `¬ internal l₀`.
      have h_len_pos : 1 ≤ e.trans.length h := by
        by_contra hc
        exact h0 (Stream'.Seq.length_le_iff.mp (Nat.lt_one_iff.mp (Nat.not_le.mp hc)).le)
      set len := e.trans.length h with hlen
      -- `e.trans.get? (len - 1)` is `some (l₀, s₀)`.
      have h_not_term : ¬ e.trans.TerminatedAt (len - 1) := by
        intro hT
        have : len ≤ len - 1 := Stream'.Seq.length_le_iff.mpr hT
        omega
      have h_exists : ∃ ls₀ : L × S, e.trans.get? (len - 1) = some ls₀ := by
        cases hg : e.trans.get? (len - 1) with
        | none => exact absurd hg h_not_term
        | some v => exact ⟨v, rfl⟩
      obtain ⟨⟨l₀, s₀⟩, h_get0⟩ := h_exists
      have h_term_len : e.trans.TerminatedAt len :=
        Stream'.Seq.length_le_iff.mp (le_refl len)
      have h_glast0 : labs.getLast? = some l₀ := by
        rw [h_glast, h_get0]; rfl
      constructor
      · rintro (hT0 | ⟨n, l, s, h_getn, h_termn, h_notint⟩)
        · exact absurd hT0 h0
        · -- Show `n = len - 1`, hence `l = l₀`.
          have h_not_termn : ¬ e.trans.TerminatedAt n := by
            intro hT
            rw [Stream'.Seq.TerminatedAt, h_getn] at hT
            exact absurd hT (by simp)
          have h_n_lt : n < len := by
            by_contra hc
            exact h_not_termn (Stream'.Seq.length_le_iff.mp (Nat.not_lt.mp hc))
          have h_len_le : len ≤ n + 1 := Stream'.Seq.length_le_iff.mpr h_termn
          have h_n_eq : n = len - 1 := by omega
          subst h_n_eq
          rw [h_get0] at h_getn
          obtain ⟨rfl, _⟩ := Prod.mk.injEq .. ▸ (Option.some.injEq ..).mp h_getn
          intro l' hl'
          rw [h_glast0] at hl'
          obtain rfl : l' = l₀ := ((Option.some.injEq ..).mp hl').symm
          exact h_notint
      · intro hall
        right
        refine ⟨len - 1, l₀, s₀, h_get0, ?_, ?_⟩
        · rw [show len - 1 + 1 = len from by omega]; exact h_term_len
        · exact hall l₀ h_glast0
  rw [part1, part2]

open Classical in
/-- **Regroup `traceProb` by label list.** Each tight, trace-`τ` execution has a
label list `labs` with `traceTightLabs τ labs`; grouping the `traceProb` sum by
`labs` yields, per such `labs`, the total `probOf`-mass of executions with label
list `labs`. -/
theorem System.traceProb_eq_labProb_sum {S L : Type} [Silent L] (ls : System S L)
    (pe : ProbabilisticExecution ls) (τ : Seq L) :
    ls.traceProb pe τ
      = ∑' labs : List L,
          (if ls.traceTightLabs τ labs then
            ∑' e : AlterSeq S L,
              dite (e.trans.Terminates ∧ e.trans.map Prod.fst = Seq.ofList labs)
                (fun h => pe.probOf e h.1) (fun _ => 0)
          else 0) := by
  classical
  unfold System.traceProb
  -- Step 1: push the `if` inside the inner `tsum`.
  rw [show (∑' labs : List L,
        (if ls.traceTightLabs τ labs then
          ∑' e : AlterSeq S L,
            dite (e.trans.Terminates ∧ e.trans.map Prod.fst = Seq.ofList labs)
              (fun h => pe.probOf e h.1) (fun _ => 0)
        else 0))
      = ∑' labs : List L, ∑' e : AlterSeq S L,
          (if ls.traceTightLabs τ labs then
            dite (e.trans.Terminates ∧ e.trans.map Prod.fst = Seq.ofList labs)
              (fun h => pe.probOf e h.1) (fun _ => 0)
          else 0) from by
    refine tsum_congr fun labs => ?_
    by_cases hc : ls.traceTightLabs τ labs
    · simp only [if_pos hc]
    · simp only [if_neg hc, tsum_zero]]
  -- Step 2: combine the double sum into a single sum over `List L × AlterSeq S L`.
  rw [← ENNReal.tsum_prod' (f := fun p : List L × AlterSeq S L =>
      if ls.traceTightLabs τ p.1 then
        dite (p.2.trans.Terminates ∧ Seq.map Prod.fst p.2.trans = (↑p.1 : Seq L))
          (fun h => pe.probOf p.2 h.1) (fun _ => 0)
      else 0)]
  -- Abbreviations for the two summands.
  set G : List L × AlterSeq S L → ENNReal := fun p =>
      if ls.traceTightLabs τ p.1 then
        dite (p.2.trans.Terminates ∧ Seq.map Prod.fst p.2.trans = (↑p.1 : Seq L))
          (fun h => pe.probOf p.2 h.1) (fun _ => 0)
      else 0 with hG_def
  -- Membership in `support G` forces both branch conditions.
  have G_supp : ∀ p : List L × AlterSeq S L, G p ≠ 0 →
      ls.traceTightLabs τ p.1 ∧
        ∃ hT : p.2.trans.Terminates, Seq.map Prod.fst p.2.trans = (↑p.1 : Seq L) := by
    intro p hp
    rw [hG_def] at hp
    simp only at hp
    by_cases hc : ls.traceTightLabs τ p.1
    · rw [if_pos hc] at hp
      by_cases hd : p.2.trans.Terminates ∧ Seq.map Prod.fst p.2.trans = (↑p.1 : Seq L)
      · exact ⟨hc, hd.1, hd.2⟩
      · rw [dif_neg hd] at hp; exact absurd rfl hp
    · rw [if_neg hc] at hp; exact absurd rfl hp
  -- From the branch conditions, recover the correspondence: `p.1 = labs` of `p.2`.
  have G_corr : ∀ p : List L × AlterSeq S L, G p ≠ 0 →
      ∃ hT : p.2.trans.Terminates,
        p.1 = (p.2.trans.toList hT).map Prod.fst ∧
        ls.trace p.2 = τ ∧ ls.IsTight p.2 := by
    intro p hp
    obtain ⟨hc, hT, hmap⟩ := G_supp p hp
    have h_p1 : p.1 = (p.2.trans.toList hT).map Prod.fst := by
      apply Stream'.Seq.ofList_injective
      rw [← System.map_ofList, Stream'.Seq.ofList_toList p.2.trans hT, hmap]
    refine ⟨hT, h_p1, ?_⟩
    have := (ls.tight_iff τ p.2 hT).mpr (h_p1 ▸ hc)
    exact ⟨this.1, this.2⟩
  refine tsum_eq_tsum_of_ne_zero_bij
    (i := fun p => (⟨(p : List L × AlterSeq S L).2,
      (G_corr p.1 p.2).choose,
      (G_corr p.1 p.2).choose_spec.2.1,
      (G_corr p.1 p.2).choose_spec.2.2⟩ :
        {e : AlterSeq S L // e.trans.Terminates ∧ ls.trace e = τ ∧ ls.IsTight e}))
    ?hinj ?hf ?hfg
  case hinj =>
    rintro ⟨p₁, hp₁⟩ ⟨p₂, hp₂⟩ heq
    -- The `AlterSeq` components agree.
    have h2 : p₁.2 = p₂.2 := congr_arg Subtype.val heq
    -- The label lists agree via injectivity of `ofList`.
    obtain ⟨_, hmap₁⟩ := (G_supp p₁ hp₁).2
    obtain ⟨_, hmap₂⟩ := (G_supp p₂ hp₂).2
    have h1 : p₁.1 = p₂.1 := by
      apply Stream'.Seq.ofList_injective
      show (↑p₁.1 : Seq L) = ↑p₂.1
      rw [← hmap₁, ← hmap₂, h2]
    have : p₁ = p₂ := Prod.ext h1 h2
    subst this; rfl
  case hf =>
    rintro ⟨e, hEprop⟩ hne
    have he_fin : e.trans.Terminates := hEprop.1
    have he_trace : ls.trace e = τ := hEprop.2.1
    have he_tight : ls.IsTight e := hEprop.2.2
    change pe.probOf e he_fin ≠ 0 at hne
    -- The preimage label list.
    set labs := (e.trans.toList he_fin).map Prod.fst with hlabs
    have h_tt : ls.traceTightLabs τ labs := (ls.tight_iff τ e he_fin).mp ⟨he_trace, he_tight⟩
    have h_map : Seq.map Prod.fst e.trans = (↑labs : Seq L) := by
      rw [hlabs, ← System.map_ofList, Stream'.Seq.ofList_toList e.trans he_fin]
    have hGne : G (labs, e) ≠ 0 := by
      rw [hG_def]
      simp only
      rw [if_pos h_tt, dif_pos ⟨he_fin, h_map⟩]
      exact hne
    exact ⟨⟨(labs, e), hGne⟩, Subtype.ext rfl⟩
  case hfg =>
    rintro ⟨p, hp⟩
    obtain ⟨hc, hT, hmap⟩ := G_supp p hp
    change pe.probOf p.2 _ = G p
    rw [hG_def]
    simp only
    rw [if_pos hc, dif_pos ⟨hT, hmap⟩]

/-! ### `probOf` is linear in the initial distribution -/

/-- `List.reverseRecOn` with a multiplicative step is linear in its base value. -/
private theorem reverseRecOn_mul_base {γ : Type*} {M : Type*} [Monoid M] (L : List γ)
    (B : M) (g : List γ → γ → M) :
    L.reverseRecOn (motive := fun _ => M) B (fun rest last ih => ih * g rest last)
      = B * L.reverseRecOn (motive := fun _ => M) 1 (fun rest last ih => ih * g rest last) := by
  induction L using List.reverseRecOn with
  | nil => rw [List.reverseRecOn_nil, List.reverseRecOn_nil, mul_one]
  | append_singleton rest last ih =>
    rw [List.reverseRecOn_concat, List.reverseRecOn_concat, ih, mul_assoc]

omit [Silent Label] in
/-- `probOf` factors through the initial mass: producing `e` from `μ_init` is
`μ_init e.init` times producing `e` from the Dirac on `e.init` (the transition
kernels depend only on the scheduler, not the initial distribution). -/
theorem ProbabilisticExecution.probOf_init_factor {Sys : System State Label}
    (sch : Scheduler Sys) (μ_init : PMF State)
    (e : AlterSeq State Label) (h : e.trans.Terminates) :
    (⟨μ_init, sch⟩ : ProbabilisticExecution Sys).probOf e h
      = μ_init e.init * (⟨PMF.pure e.init, sch⟩ : ProbabilisticExecution Sys).probOf e h := by
  have hbase : (⟨μ_init, sch⟩ : ProbabilisticExecution Sys).init e.init = μ_init e.init := rfl
  have hbase' : (⟨PMF.pure e.init, sch⟩ : ProbabilisticExecution Sys).init e.init = 1 :=
    PMF.pure_apply_self e.init
  have hker : ∀ rest last,
      (⟨PMF.pure e.init, sch⟩ : ProbabilisticExecution Sys).kernel ⟨e.init, Seq.ofList rest⟩ last
      = (⟨μ_init, sch⟩ : ProbabilisticExecution Sys).kernel ⟨e.init, Seq.ofList rest⟩ last :=
    fun _ _ => rfl
  unfold ProbabilisticExecution.probOf
  rw [hbase, hbase']
  simp only [hker]
  exact reverseRecOn_mul_base (e.trans.toList h) (μ_init e.init)
    (fun rest last =>
    (⟨μ_init, sch⟩ : ProbabilisticExecution Sys).kernel ⟨e.init, Seq.ofList rest⟩ last)

omit [Silent Label] in
/-- **`probOf` is linear in the initial distribution.** Producing the execution
`e` from a mixture `μ_init` is the `μ_init`-average of producing it from each
Dirac start. The "un-disintegration" identity used to glue weak-τ phases. -/
theorem ProbabilisticExecution.probOf_init_mix {Sys : System State Label}
    (sch : Scheduler Sys) (μ_init : PMF State)
    (e : AlterSeq State Label) (h : e.trans.Terminates) :
    (⟨μ_init, sch⟩ : ProbabilisticExecution Sys).probOf e h
      = ∑' s, μ_init s * (⟨PMF.pure s, sch⟩ : ProbabilisticExecution Sys).probOf e h := by
  classical
  rw [tsum_eq_single e.init (fun s hs => by
    rw [ProbabilisticExecution.probOf_init_factor sch (PMF.pure s) e h,
      PMF.pure_apply_of_ne _ _ (Ne.symm hs), zero_mul, mul_zero])]
  exact ProbabilisticExecution.probOf_init_factor sch μ_init e h

end PLTS
