/-
Copyright (c) 2026 Gaspard Reghem. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Gaspard Reghem
-/

import MyMathlibProject.Construction.LowerGen
import MyMathlibProject.Construction.DistFair
import MyMathlibProject.Model.ResolvedScheduler

/-!
# Superset direction of the fair `𝒟f`-equivalence (resolved schedulers)

This file targets the hard **superset** inclusion of the fair distribution-monad equivalence, under
the resolved-scheduler semantics:

  `fairAchievableTraceDists F.dist ⊆ fairAchievableTraceDists F`.

Given a fair resolved `𝒟f(sys,F)`-execution `PE'` achieving trace distribution `D`, we reconstruct a
fair resolved `sys`-execution achieving `D`. The Dirac lift (`Construction/DistFair.lean`) already
gives the reverse inclusion, so this closes the equivalence.

## The two witnesses and where the residue lives

`(sys.distF F).step` is definitionally `𝒟(sys).step` plus a `Resolvable` side-condition, so `PE'`'s
emissions are valid `𝒟(sys)`-steps and the proven plain reconstruction
`ProbabilisticExecution.lower` (`Construction/DistTrace.lean`) applies to the forgetful reading of
`PE'.average`.

* **`lowerCoe` — the μ-blind baseline.** Coercing that plain reconstruction back to a resolved
  execution realises `PE'`'s trace **for free** (`lowerCoe_traceProbR`, via `traceProbR_toResolved`
  + `lower_traceProb_eq` + `traceProb_average`). But its scheduler ignores the recorded `μ`s (it
  factors through `r.toExec`), so its consistency collapses to the plain reconstruction's, which is
  not fair (the plain superset is false, `Model/ResolvedGap.lean`); its support admits an
  eventually-all-unfair "chimera" run. Kept only as the documented baseline.

* **`lowerFairR` — the μ-reading witness.** It conditions on the *full* resolved history `r`
  (recorded `μ`s included) through a coherence filter `RCoherent` on the trace-cone belief, so an
  unrealisable `μ`-pattern reconstructs to empty restricted belief-support and the naive chimeras
  are killed; its emission uses the fairness-revealing kernel `distFairHyperKernel`
  (`Construction/DistFair.lean`-style). Its `valid` reduces to `distFairHyperKernel_valid` (the
  filter only shrinks the belief support). This is the witness the superset theorem uses.

The residue is **two genuine cruxes** plus **one mechanical residue**, each a documented `sorry`:

* **Crux A — trace faithfulness** (`lowerFairR_traceProbR`, **no finiteness**): the filter excludes
  non-liftable runs and redistributes their label-mass onto liftable runs; matching the result to
  `PE'.traceProbR` is a genuine resolved trace-cone / probability-matching argument (finite runs
  lift trivially, so no finiteness is needed).
* **Crux B — phantom-freeness** (`lowerFairR_phantom_free`, **consumes a tightness input, no
  `[Fintype State]`**): every infinite consistent concrete run lifts to *one* coherent infinite
  `PE'`-belief-run (fair by `PE'.IsFair.inf_fair`; the fairness-revealing `μ` carries `F.dist`-
  fairness to `FairStepAt`); the lift is a relative-compactness (Prokhorov) extraction over
  `PMF State`, whose minimal input is `PE'.ReachBeliefsTight F` (tightness of the reachable
  beliefs), threaded through as a hypothesis rather than baked in as finiteness.
* **The halt clause** (`lowerFairR_halt_fairDeadlock`) — *not* a genuine crux, a mechanical residue.
  `halt_fairDeadlock` is quantified over `Consistent` runs, on which the `PMF.pure none` fallback is
  **vacuous** (a consistent `r` is generated by coherent belief-histories, so its restricted belief
  support is non-empty); discharging it needs a *qualitative* reachability lemma ("a consistent `r`
  admits a coherent belief-history" — support-level, strictly weaker than crux A's quantitative
  matching), and the realisable branch needs the `𝒟f→𝒟` fair-deadlock transfer through
  `PE'.average` (`PE'.IsFair.halt_fairDeadlock` + `distF_fairDeadlock_belief`). Both are
  reachability bookkeeping, `[Fintype State]`-free; it was never separately proven for `lowerCoe`
  either (it sat inside the old bundled `sorry`), so isolating it here is no regression.

### On finiteness (compactness is the real need, not finite branching)

Crux B lifts a concrete run to a consistent `PE'`-belief-run. That lift's tree branches over
`ω : PMF (PMF State)` and successor beliefs `ν : PMF State` — **continuum-valued even when `sys` is
image-finite** (one concrete run observes one state per step, but a belief depends on the kernel's
action on *unobserved* states). So König (`exists_infinite_chain`) is the wrong tree, and
`ImageFinite` is **neither necessary nor sufficient** — it finitizes the *state* tree, not the
*belief* tree, which stays continuum-branching. What the lift actually needs is not finite branching
but **relative compactness** of the reachable-belief family, i.e. tightness (`ReachBeliefsTight`).
That is threaded as the hypothesis `hT` into `lowerFairR_phantom_free` / `lowerFairR_isFair` /
`fairAchievableTraceDists_superset_distF`, all of which are therefore **`[Fintype State]`-free**.
`[Fintype State]` is merely the crudest sufficient discharge, confined to the single lemma
`lowerFairR_reachBeliefsTight_of_fintype` (and the corollary
`fairAchievableTraceDists_superset_distF_of_fintype`); a genuine tightness condition on `sys`
discharges `hT` with `State` infinite (unconditional tightness is false — beliefs may escape to
infinity). The construction, `initState`, halt clause, and crux A never mention it.
-/

open Stream'

namespace PLTS

variable {State Label : Type} [Silent Label]

/-! ### Forgetting `𝒟f(sys,F)` to `𝒟(sys)`

`traceProb`/`probOf`/`kernel` never inspect the step relation (only `Scheduler.valid` does), so a
`𝒟f(sys,F)`-execution *forgets* into a `𝒟(sys)`-execution for free by weakening the validity witness
`(sys.distF F).step ⇒ 𝒟(sys).step` (drop the `Resolvable` conjunct). -/

/-- The forgetful coercion of a plain `𝒟f(sys,F)`-execution to a plain `𝒟(sys)`-execution: same
initial distribution and same scheduler emissions, with the validity obligation weakened from a
`distF`-step to its underlying `hyperStep` (= `𝒟(sys)`-step). -/
noncomputable def ProbabilisticExecution.distFToDist {sys : System State Label} (F : Fairness sys)
    (pe : ProbabilisticExecution (sys.distF F)) : ProbabilisticExecution 𝒟(sys) where
  initState := pe.initState
  scheduler :=
    { next := pe.scheduler.next
      valid := fun e n s hterm hstate l μ hsupp =>
        (pe.scheduler.valid e n s hterm hstate l μ hsupp).1 }

@[simp] theorem ProbabilisticExecution.distFToDist_initState {sys : System State Label}
    (F : Fairness sys) (pe : ProbabilisticExecution (sys.distF F)) :
    (pe.distFToDist F).initState = pe.initState := rfl

/-- `distFToDist` preserves the plain trace distribution: `traceProb` never inspects the step
relation, only the scheduler and initial distribution (both unchanged), and `trace`/`IsTight` depend
only on the label type — so the two sides are definitionally equal. -/
theorem ProbabilisticExecution.distFToDist_traceProb {sys : System State Label} (F : Fairness sys)
    (pe : ProbabilisticExecution (sys.distF F)) (τ : Seq Label) :
    (sys.distF F).traceProb pe τ = 𝒟(sys).traceProb (pe.distFToDist F) τ := rfl

/-! ### The fairness-revealing decomposition kernel

`distFairHyperKernel` is a `lowerWith`-kernel that reveals fairness: at an emission `(l, ω)` whose
end-state belief `F.dist`-*fairly*-enables `(l, ω)`, it returns the all-`F`-fair realizer `p` of
that fair step (so every produced `sys`-step is `F`-fair); otherwise it falls back to the generic
`distHyperKernel`. Either way it has the same post-marginal `ω.bind id`, so it satisfies the same
validity and marginal-decomposition obligations as `distHyperKernel`. -/

open Classical in
/-- The **fairness-revealing decomposition kernel**. On the fair branch (the end-state belief
`F.dist`-fairly-enables the emission `(l, ω)`) it returns the all-`F`-fair realizer of that fair
step; otherwise it is the generic `distHyperKernel`. Its post-marginal is `ω.bind id` in both
branches. -/
noncomputable def ProbabilisticExecution.distFairHyperKernel {sys : System State Label}
    (F : Fairness sys) (pe' : ProbabilisticExecution 𝒟(sys))
    (E : AlterSeq (PMF State) Label) (l : Label) (ω : PMF (PMF State)) :
    State → PMF (PMF State) :=
  if h : ∃ hE : E.trans.Terminates, (F.dist).fair (E.endState hE) l ω then
    h.choose_spec.2.choose
  else
    pe'.distHyperKernel E l ω

/-- **Validity of `distFairHyperKernel`.** Every distribution in the fairness-revealing kernel's
support is a valid `sys`-step post-distribution: on the fair branch it is an all-`F`-fair realizer
(hence `F`-fair, hence a `sys`-step via `step_of_fair`); on the else branch it inherits validity
from `distHyperKernel_step`. -/
theorem ProbabilisticExecution.distFairHyperKernel_valid {sys : System State Label}
    (F : Fairness sys) (pe' : ProbabilisticExecution 𝒟(sys)) :
    LowerKernelValid pe' (pe'.distFairHyperKernel F) := by
  classical
  intro E hE l ω h_supp s hs μ hμ
  by_cases h : ∃ hE' : E.trans.Terminates, (F.dist).fair (E.endState hE') l ω
  · -- Fair branch: the kernel is the all-`F`-fair realizer `p := h.choose_spec.2.choose`.
    set p := h.choose_spec.2.choose with hp_def
    have hp_fair : ∀ s ∈ (E.endState h.choose).support, ∀ μ' ∈ (p s).support, F.fair s l μ' :=
      h.choose_spec.2.choose_spec.1
    have h_def : pe'.distFairHyperKernel F E l ω = p := by
      unfold ProbabilisticExecution.distFairHyperKernel
      rw [dif_pos h]
    rw [h_def] at hμ
    -- Reconcile the two `Terminates` proofs so `s ∈ (E.endState h.choose).support`.
    have h_choose : h.choose = hE := Subsingleton.elim _ _
    rw [← h_choose] at hs
    exact F.step_of_fair s l μ (hp_fair s hs μ hμ)
  · -- Else branch: the kernel is `distHyperKernel`.
    have h_def : pe'.distFairHyperKernel F E l ω = pe'.distHyperKernel E l ω := by
      unfold ProbabilisticExecution.distFairHyperKernel
      rw [dif_neg h]
    rw [h_def] at hμ
    exact pe'.distHyperKernel_step hE h_supp hs hμ

/-- **Marginal decomposition of `distFairHyperKernel`.** Integrating the fairness-revealing
per-state kernel `bind id` against the end-state distribution recovers `ω.bind id`: on the fair
branch this is the realizer bind-equality conjunct of `F.dist.fair`, on the else branch it is
`hyperStep_marginal_decomp`. -/
theorem ProbabilisticExecution.distFairHyperKernel_decomp {sys : System State Label}
    (F : Fairness sys) (pe' : ProbabilisticExecution 𝒟(sys)) :
    LowerKernelDecomp pe' (pe'.distFairHyperKernel F) := by
  classical
  intro E hE l ω h_supp q
  by_cases h : ∃ hE' : E.trans.Terminates, (F.dist).fair (E.endState hE') l ω
  · -- Fair branch: the kernel is the all-`F`-fair realizer `p := h.choose_spec.2.choose`.
    set p := h.choose_spec.2.choose with hp_def
    have hp_eq : ω.bind id = (E.endState h.choose).bind (fun s => (p s).bind id) :=
      h.choose_spec.2.choose_spec.2
    have h_def : pe'.distFairHyperKernel F E l ω = p := by
      unfold ProbabilisticExecution.distFairHyperKernel
      rw [dif_pos h]
    -- Reconcile the two `Terminates` proofs.
    have h_choose : h.choose = hE := Subsingleton.elim _ _
    rw [h_def, ← h_choose]
    conv_lhs => rw [hp_eq]
    rw [PMF.bind_apply]
  · -- Else branch: the kernel is `distHyperKernel`; use `hyperStep_marginal_decomp`.
    have h_def : pe'.distFairHyperKernel F E l ω = pe'.distHyperKernel E l ω := by
      unfold ProbabilisticExecution.distFairHyperKernel
      rw [dif_neg h]
    rw [h_def]
    exact pe'.hyperStep_marginal_decomp hE h_supp q

/-! ### The trace side: the coercion witness (`lowerCoe`)

`lowerCoe` realises `PE'`'s trace distribution as a resolved `sys`-execution, reusing the plain
reconstruction. It is **not** sure-fair (see the module docstring); it exists only to show the trace
half is free. -/

/-- The **coercion (trace) witness**: the plain trace-cone reconstruction `lower` of the forgetful
reading of `PE'.average`, coerced to a resolved execution. Realises `PE'`'s trace distribution but
is not sure-fair. -/
noncomputable def ResolvedProbabilisticExecution.lowerCoe {sys : System State Label}
    (F : Fairness sys) (PE' : ResolvedProbabilisticExecution (sys.distF F)) :
    ResolvedProbabilisticExecution sys :=
  (((PE'.average).distFToDist F).lower).toResolved

/-- The coercion witness realises `PE'`'s trace distribution — the trace half of the superset, free
via `traceProbR_toResolved`, `lower_traceProb_eq`, `distFToDist_traceProb`, `traceProb_average`. -/
theorem ResolvedProbabilisticExecution.lowerCoe_traceProbR {sys : System State Label}
    (F : Fairness sys) (PE' : ResolvedProbabilisticExecution (sys.distF F)) (τ : Seq Label) :
    (PE'.lowerCoe F).traceProbR τ = PE'.traceProbR τ := by
  rw [ResolvedProbabilisticExecution.lowerCoe,
    ProbabilisticExecution.traceProbR_toResolved,
    ProbabilisticExecution.lower_traceProb_eq,
    ← ProbabilisticExecution.distFToDist_traceProb, PE'.traceProb_average τ]

/-- The coercion witness starts from the Dirac initial distribution `pure sys.init`. -/
theorem ResolvedProbabilisticExecution.lowerCoe_initState {sys : System State Label}
    (F : Fairness sys) (PE' : ResolvedProbabilisticExecution (sys.distF F))
    (hinit : PE'.initState = PMF.pure (sys.distF F).init) :
    (PE'.lowerCoe F).initState = PMF.pure sys.init := by
  change PE'.initState.bind id = PMF.pure sys.init
  rw [hinit, PMF.pure_bind]
  rfl

/-! ### Fair-enabledness of a resolvable belief -/

/-- If a belief `ν` has a **common fair label** `l` (every state in its support fair-enables `l`),
then `ν` is `F.dist`-fair-enabled: the belief-step to `(ν.bind μ).map PMF.pure` — clustering the
common per-state fair kernel `μ` down to Diracs — is `F.dist`-fair. -/
theorem Fairness.commonFairLabel_distFairEnabled {sys : System State Label} (F : Fairness sys)
    {ν : PMF State} (h : F.CommonFairLabel ν) : (F.dist).FairEnabled ν := by
  classical
  obtain ⟨l, hl⟩ := h
  choose! μ hμ using hl
  -- The flattened target `ν.bind μ`, clustered to Diracs and then flattened back, is `ν.bind μ`.
  have hkey : ((ν.bind μ).map PMF.pure).bind id = ν.bind μ := by
    rw [PMF.bind_map]; exact PMF.bind_pure (ν.bind μ)
  -- The witness step, kernel and per-state fair kernel `p := fun s => PMF.pure (μ s)`.
  refine ⟨l, (ν.bind μ).map PMF.pure, ⟨⟨fun s => PMF.pure (μ s), ?_, ?_⟩, ?_⟩,
    fun s => PMF.pure (μ s), ?_, ?_⟩
  · -- `hyperStep` validity: `μ' = μ s`, and `sys.step s l (μ s)` from fairness.
    intro s hs μ' hμ'
    rw [PMF.mem_support_pure_iff] at hμ'
    subst hμ'
    exact F.step_of_fair s l (μ s) (hμ s hs)
  · -- `hyperStep` post-equality: `PMF.pure (μ s)).bind id = μ s`, then `hkey`.
    rw [hkey]
    simp only [PMF.pure_bind, Function.id_def]
  · -- Every successor belief is a Dirac, hence resolvable.
    intro ν' hν'
    rw [PMF.mem_support_map_iff] at hν'
    obtain ⟨t, _, rfl⟩ := hν'
    exact F.resolvable_pure t
  · -- The all-fair conjunct of `Fairness.dist.fair`: `μ' = μ s`, fair from `hμ`.
    intro s hs μ' hμ'
    rw [PMF.mem_support_pure_iff] at hμ'
    subst hμ'
    exact hμ s hs
  · -- The bind-equality conjunct: same clustering computation as the `hyperStep` post-equality.
    rw [hkey]
    simp only [PMF.pure_bind, Function.id_def]

/-- If a resolvable belief `ν` is a `F.dist`-fair-deadlock, every state in `ν.support` is an
`F`-fair-deadlock. Resolvability forces the dichotomy: a common fair label would make `ν`
`F.dist`-fair-enabled (`commonFairLabel_distFairEnabled`), contradicting the deadlock; so `ν`
must be a genuine (all-states) fair deadlock, which is exactly the goal. -/
theorem Fairness.distF_fairDeadlock_belief {sys : System State Label} (F : Fairness sys)
    {ν : PMF State} (hres : F.Resolvable ν) (hdl : (F.dist).FairDeadlock ν) :
    ∀ s ∈ ν.support, F.FairDeadlock s := by
  rcases hres with hcfl | hafd
  · exact absurd (F.commonFairLabel_distFairEnabled hcfl) hdl
  · exact hafd

/-! ### The `μ`-reading witness `lowerFairR`

`lowerCoe` above is the **μ-blind** baseline: its scheduler ignores the recorded `μ`s (it factors
through `r.toExec`), so its support admits eventually-all-unfair "chimera" runs and it is not
sure-fair. `lowerFairR` is the **μ-reading** upgrade: it conditions on the *full* resolved history
`r` (including the recorded `μ`s) through a coherence filter `RCoherent`, so an unrealisable
`μ`-pattern reconstructs to empty restricted belief-support and the naive chimeras are killed. Its
emission then uses the fairness-revealing kernel `distFairHyperKernel`, exactly as `lowerCoe`'s
underlying `lowerWith distFairHyperKernel` would. -/

/-- **Coherence of a belief-history `E` with a resolved history `r`.** Every resolved transition
`((l, μ), s')` recorded in `r` at position `n`, from the concrete state `s = r.stateAt n`, has its
chosen distribution `μ` reproduced by the fairness-revealing kernel `distFairHyperKernel` at that
concrete state, for *some* belief emission `(l, ω)` of `PE'.average` at `E`.

This predicate is a genuine function of the **full** `r` — it reads `r.trans`'s recorded `μ`s, not
only `r.toExec` — which is precisely what makes `lowerFairR` μ-reading: a resolved history whose
`μ`-pattern is not `distFairHyperKernel`-realisable satisfies `RCoherent` for no `E`, so the
filtered belief-support is empty and the chimera is removed. (The `E`-argument is present so the
predicate can filter `beliefTC`; its content lives in `r`, which is the simplest coherence filter
that both genuinely reads `r` and leaves the `valid` proof reducible to `distFairHyperKernel_valid`
— the filter only *shrinks* the belief support.) -/
def ResolvedProbabilisticExecution.RCoherent {sys : System State Label} (F : Fairness sys)
    (PE' : ResolvedProbabilisticExecution (sys.distF F)) (r : ResolvedExec State Label)
    (E : AlterSeq (PMF State) Label) : Prop :=
  ∀ (n : ℕ) (s : State) (l : Label) (μ : PMF State) (s' : State),
    r.stateAt n = some s → r.trans.get? n = some ((l, μ), s') →
      ∃ ω : PMF (PMF State),
        some (l, ω) ∈ ((PE'.average.distFToDist F).scheduler.next E).support ∧
          μ ∈ ((PE'.average.distFToDist F).distFairHyperKernel F E l ω s).support

/-- The **μ-reading resolved witness scheduler.** Mirrors `Scheduler.lower`
(`Construction/DistTrace.lean`) on the forgetful reading `PE'.average.distFToDist F`, but the
belief-history `E` is sampled from the trace-cone belief *restricted* to those `E` coherent with the
full resolved history `r` (`RCoherent`), so it reads the recorded `μ`s. The emission uses the
fairness-revealing kernel `distFairHyperKernel`. When the restricted mass is `0` (the `μ`-pattern is
unrealisable) it halts (`PMF.pure none`).

`valid` mirrors `Scheduler.lower`'s: the coherence restriction only shrinks the belief support, so
`beliefTC_support` still supplies `s ∈ E.endState.support` and validity reduces to
`distFairHyperKernel_valid`. -/
noncomputable def ResolvedProbabilisticExecution.lowerFairRSched {sys : System State Label}
    (F : Fairness sys) (PE' : ResolvedProbabilisticExecution (sys.distF F)) :
    ResolvedScheduler sys where
  next r :=
    open Classical in
    if h_term : r.toExec.trans.Terminates then
      if h0 : (∑' E, Set.indicator {E | PE'.RCoherent F r E}
          ((PE'.average.distFToDist F).beliefTC ((r.toExec.trans.toList h_term).map Prod.fst)
            (r.toExec.endState h_term)) E) ≠ 0 then
        (((PE'.average.distFToDist F).beliefTC ((r.toExec.trans.toList h_term).map Prod.fst)
            (r.toExec.endState h_term)).filter {E | PE'.RCoherent F r E}
          (by
            obtain ⟨E, hE⟩ := not_forall.mp (mt ENNReal.tsum_eq_zero.mpr h0)
            obtain ⟨hmem, hsupp⟩ := Set.indicator_apply_ne_zero.mp hE
            exact ⟨E, hmem, hsupp⟩)).bind (fun E =>
          ((PE'.average.distFToDist F).scheduler.next E).bind (fun opt =>
            match opt with
            | none         => PMF.pure none
            | some (l, ω)  =>
              ((PE'.average.distFToDist F).distFairHyperKernel F E l ω
                  (r.toExec.endState h_term)).map (fun μ' => some (l, μ'))))
      else
        PMF.pure none
    else
      PMF.pure none
  valid := by
    classical
    intro r n s r_term_n r_stateAt_eq l μ h_supp
    have h_term_e : r.toExec.trans.Terminates :=
      (ResolvedExec.toExec_terminates_iff r).mpr ⟨n, r_term_n⟩
    have h_term : r.trans.Terminates := ⟨n, r_term_n⟩
    -- Reduce `r.stateAt`/`r.trans.TerminatedAt` to `r.toExec`'s, then reuse the `lower` shape.
    have e_term_n : r.toExec.trans.TerminatedAt n :=
      (ResolvedExec.toExec_terminatedAt_iff r n).mpr r_term_n
    have e_stateAt_eq : r.toExec.stateAt n = some s := by
      rw [ResolvedExec.toExec_stateAt]; exact r_stateAt_eq
    have h_find_le : Nat.find h_term_e ≤ n := Nat.find_le e_term_n
    have h_n_le : n ≤ Nat.find h_term_e := by
      by_contra h_lt
      push Not at h_lt
      rcases n with _ | k
      · exact absurd h_lt (Nat.not_lt_zero _)
      · have hk_ge : Nat.find h_term_e ≤ k := Nat.lt_succ_iff.mp h_lt
        have h_term_k : r.toExec.trans.TerminatedAt k :=
          Stream'.Seq.terminated_stable r.toExec.trans hk_ge (Nat.find_spec h_term_e)
        have h_state_none : r.toExec.stateAt (k + 1) = none := by
          change (r.toExec.trans.get? k).map Prod.snd = none
          rw [show r.toExec.trans.get? k = none from h_term_k]
          rfl
        rw [h_state_none] at e_stateAt_eq
        exact Option.some_ne_none s e_stateAt_eq.symm
    have h_n_eq : n = Nat.find h_term_e := le_antisymm h_n_le h_find_le
    have h_s_eq : s = r.toExec.endState h_term_e := by
      have h := AlterSeq.stateAt_find_eq_endState r.toExec h_term_e
      rw [← h_n_eq] at h
      rw [h] at e_stateAt_eq
      exact (Option.some.inj e_stateAt_eq).symm
    subst h_s_eq
    set pe' := PE'.average.distFToDist F with hpe'
    -- Unfold the emission; the coherence filter only shrinks `beliefTC`'s support.
    change some (l, μ) ∈
      (open Classical in
        if h_term' : r.toExec.trans.Terminates then
          if h0 : (∑' E, Set.indicator {E | PE'.RCoherent F r E}
              (pe'.beliefTC ((r.toExec.trans.toList h_term').map Prod.fst)
                (r.toExec.endState h_term')) E) ≠ 0 then
            ((pe'.beliefTC ((r.toExec.trans.toList h_term').map Prod.fst)
                (r.toExec.endState h_term')).filter {E | PE'.RCoherent F r E} _).bind (fun E =>
              (pe'.scheduler.next E).bind (fun opt =>
                match opt with
                | none         => PMF.pure none
                | some (l', ω) =>
                  (pe'.distFairHyperKernel F E l' ω (r.toExec.endState h_term')).map
                    (fun μ' => some (l', μ'))))
          else PMF.pure none
        else PMF.pure none).support at h_supp
    rw [dif_pos h_term_e] at h_supp
    split_ifs at h_supp with h0
    · rw [PMF.mem_support_bind_iff] at h_supp
      obtain ⟨E, hE_belief, h_supp⟩ := h_supp
      rw [PMF.mem_support_filter_iff] at hE_belief
      obtain ⟨-, hE_belief⟩ := hE_belief
      rw [PMF.mem_support_bind_iff] at h_supp
      obtain ⟨opt, hopt_sch, h_supp⟩ := h_supp
      obtain ⟨hE_term, h_endState⟩ :=
        pe'.beliefTC_support ((r.toExec.trans.toList h_term_e).map Prod.fst)
          (r.toExec.endState h_term_e) hE_belief
      cases opt with
      | none =>
        change some (l, μ) ∈ (PMF.pure (α := Option (Label × PMF State)) none).support at h_supp
        rw [PMF.support_pure, Set.mem_singleton_iff] at h_supp
        exact absurd h_supp (by simp)
      | some lω =>
        obtain ⟨l', ω⟩ := lω
        change some (l, μ) ∈ ((pe'.distFairHyperKernel F E l' ω (r.toExec.endState h_term_e)).map
          (fun μ' => some (l', μ'))).support at h_supp
        rw [PMF.mem_support_map_iff] at h_supp
        obtain ⟨μ', h_μ'_kernel, h_eq⟩ := h_supp
        simp only [Option.some.injEq, Prod.mk.injEq] at h_eq
        obtain ⟨rfl, rfl⟩ := h_eq
        exact pe'.distFairHyperKernel_valid F hE_term hopt_sch h_endState h_μ'_kernel
    · change some (l, μ) ∈ (PMF.pure (α := Option (Label × PMF State)) none).support at h_supp
      rw [PMF.support_pure, Set.mem_singleton_iff] at h_supp
      exact absurd h_supp (by simp)

/-- The **μ-reading resolved witness execution**: initial distribution `PE'.initState.bind id`
(a Dirac on `sys.init` under the `fairAchievableTraceDists` requirement), with scheduler
`lowerFairRSched`. Reads the recorded `μ`s (via the `RCoherent` filter), killing the naive chimeras
that `lowerCoe` admits. -/
noncomputable def ResolvedProbabilisticExecution.lowerFairR {sys : System State Label}
    (F : Fairness sys) (PE' : ResolvedProbabilisticExecution (sys.distF F)) :
    ResolvedProbabilisticExecution sys :=
  ⟨PE'.initState.bind id, PE'.lowerFairRSched F⟩

/-- The μ-reading witness starts from the Dirac initial distribution `pure sys.init` (same one-line
proof as `lowerCoe_initState`: `initState = PE'.initState.bind id`, then `hinit`,
`PMF.pure_bind`). -/
theorem ResolvedProbabilisticExecution.lowerFairR_initState {sys : System State Label}
    (F : Fairness sys) (PE' : ResolvedProbabilisticExecution (sys.distF F))
    (hinit : PE'.initState = PMF.pure (sys.distF F).init) :
    (PE'.lowerFairR F).initState = PMF.pure sys.init := by
  change PE'.initState.bind id = PMF.pure sys.init
  rw [hinit, PMF.pure_bind]
  rfl

/-! ### Crux A — trace faithfulness (no finiteness) -/

/-- **Crux A: the μ-reading witness realises `PE'`'s trace distribution.** Unlike `lowerCoe` (which
inherits its trace for free from the plain reconstruction), `lowerFairR` *excludes* the
non-liftable (chimera) belief-runs through the `RCoherent` filter and redistributes their
label-mass onto the liftable runs. Proving that the restricted-and-refair-ed reconstruction still
reproduces `PE'`'s trace is a genuine **resolved trace-cone / probability-matching** argument: it
matches the filtered belief-cone mass against `PE'.traceProbR` step by step. Finite runs lift
trivially (a finite `μ`-pattern is always realisable), so **no finiteness hypothesis is needed**.
Left as a documented `sorry`. -/
theorem ResolvedProbabilisticExecution.lowerFairR_traceProbR {sys : System State Label}
    (F : Fairness sys) (PE' : ResolvedProbabilisticExecution (sys.distF F))
    (hinit : PE'.initState = PMF.pure (sys.distF F).init) (τ : Seq Label) :
    (PE'.lowerFairR F).traceProbR τ = PE'.traceProbR τ := by
  sorry

/-! ### The halt clause (mechanical residue, documented `sorry`)

`halt_fairDeadlock` is quantified over `Consistent` runs, and this is *not* a genuine crux — it is
reachability bookkeeping. Two branches:
* **Realisable** (restricted belief-mass positive): factors, exactly like `lowerWith_next_none`,
  through a coherent belief-history `E` at which `PE'.average` halts, then the `𝒟f→𝒟` fair-deadlock
  transfer (`PE'.IsFair.halt_fairDeadlock` + `distF_fairDeadlock_belief`, the resolvable
  belief-deadlock transfer) carries the deadlock down to the concrete end-state — pure reuse.
* **Fallback** (`RCoherent`-restricted mass `0`, witness emits `PMF.pure none`): **vacuous** on a
  `Consistent` `r`. A consistent run is *generated* by coherent belief-histories, so its restricted
  belief support is non-empty and the fallback never fires; making that formal needs only a
  *qualitative* reachability lemma ("a consistent `r` admits a coherent belief-history" —
  support-level, strictly weaker than crux A's quantitative probability-matching).
Both halves are `[Fintype State]`-free reachability bookkeeping; the clause was never separately
proven for `lowerCoe` either (it lived inside the old bundled `sorry`). Isolated here as a `sorry`,
distinct from the two genuine cruxes. -/

/-- **The witness halts only from a fair deadlock.** If the μ-reading witness halts at a terminating
consistent run `r`, its end-state `r.endState` is an `F`-fair-deadlock. Mechanical residue (see the
section doc): realisable branch = `𝒟f→𝒟` deadlock transfer reuse; fallback branch = vacuous on
`Consistent` runs, needing a support-level reachability lemma. Left as a documented `sorry`. -/
theorem ResolvedProbabilisticExecution.lowerFairR_halt_fairDeadlock {sys : System State Label}
    (F : Fairness sys) (PE' : ResolvedProbabilisticExecution (sys.distF F))
    (hfair : PE'.IsFair F.dist) (r : ResolvedExec State Label) (h : r.trans.Terminates)
    (_hcons : (PE'.lowerFairR F).Consistent r)
    (h_none : (PE'.lowerFairR F).scheduler.next r none ≠ 0) :
    F.FairDeadlock (r.endState h) := by
  sorry

/-! ### Design notes — assumptions for discharging crux B (`lowerFairR_phantom_free`)

Summary of the design discussion on what to assume to close phantom-freeness. There are two proof
routes; both terminate at the same residual crux. This block is a reading aid, not code.

**The obstruction.** The lift takes an infinite consistent concrete run `r` and must produce ONE
coherent infinite `PE'`-belief-run. Building it as a limit of finite coherent prefixes risks a
*phantom*: the limit belief-run leaves the reachable/consistent set of `PE'`, so it is not a genuine
`PE'`-run and `PE'.IsFair.inf_fair` does not apply to it.

**Where the scheduler is evaluated (the space in play).** `PE'.scheduler.next` acts on *resolved
belief-executions* `ResolvedExec (PMF State) Label`, i.e.
`AlterSeq (PMF State) (Label × PMF (PMF State))`.
The topology that matters lives only on the continuous coordinates — beliefs `ν : PMF State` and
recorded hyper-distributions `ω : PMF (PMF State)`, each with the weak topology (finite `State`:
Euclidean simplices); length and labels are discrete. "Continuity of the scheduler in the belief"
means continuity in those coordinates, and it is NOT automatic — a scheduler is an arbitrary
function of the whole history.

**Route A — compactness / tightness (this is what `ReachBeliefsTight` below encodes).** Extract a
convergent subsequence of coherent prefixes and take limits. Three inputs:
* (i) relative compactness of the reachable beliefs = `ReachBeliefsTight` (Prokhorov). `[Fintype
  State]` is only the crudest discharge; it does NOT make the belief tree finitely-branching — that
  tree is continuum-branching even for two states. `System.ImageFinite` is neither necessary nor
  sufficient here: it finitizes the *state* tree, not the *belief* tree.
* (ii) codomain hygiene: bounded-arity `ω` makes the `ω`-space compact/closed, so weak limits of
  recorded `ω`'s stay legal `PMF`s (else a limit `ω` can be a non-discrete measure). Per-`ω` finite
  support is NOT enough — a *uniform* arity bound is needed.
* (iii) closedness of the coherence constraints under limits. This is the hard residual, and
  tightness does NOT supply it: `next` can jump, and consistency of the limit run re-evaluates
  `next` at the limit history, so a discontinuity yields a phantom. Tightness gives a compact space
  to land in, not a continuous map into it.

**Route B — König / finite branching.** Work in the resolved-execution tree; length is discrete, so
the sharp question is *per length*: is the reachable set closed and separated? In a compact
per-length space, closed + discrete = finite, hence
  closed+separated per length  ⟺  finitely-many-per-length  ⟺  finite branching  ⟺  König
(`exists_infinite_chain`). Closed alone already kills the phantom; separated is overkill.
* Sufficient assumptions: image-finite `sys` + finite mass-splitting (each `ω` finite support) +
  bound the number of scheduled transitions per `(ω.bind id).support` at each node. Then per node
  the outcomes have support `⊆ Succ(ν)` (finite, from finite `sys`), so finitely many support
  classes; times finitely many transitions per class ⟹ finite branching ⟹ König. No tightness, no
  continuity.
* TWO complementary axes must both be bounded: finite `sys` bounds the number of support classes
  (the "which successor states" axis); the per-`(ω.bind id).support` restriction bounds transitions
  within a class (the "which split/weights" axis). Drop the restriction ⟹ same-support accumulation;
  drop finite `sys` ⟹ cross-support accumulation (`μₖ = (1−1/k)·δ_a + (1/k)·δ_{bₖ} → δ_a`, distinct
  `bₖ`). Either omission alone breaks closedness.

**Why not merge / normal-form the splits.** Collapsing accumulating `ω`'s (e.g. a distinct-support
normal form) fixes the topology and preserves the trace (trace is affine, insensitive to
resolution), but it DESTROYS sure fairness. This is the fundamental tension: the recorded resolution
is simultaneously (a) what sure fairness needs — to exclude the eventually-all-unfair chimeras from
the support and schedule each branch fairly — and (b) what breaks the topology (accumulating
splits).
The fair-marking itself is flattened-determined: `F.dist.fair ν l ω` depends on `ω` only through
`ω.bind id`. So resolution is never needed for *whether a step is fair*; it is needed only to shape
the *support* (consistency). That is exactly why merging is fatal and the difficulty is real.

**The residual crux (either route).** Each option is a *restriction on `PE'`*. The full superset
needs it to hold WITHOUT LOSS:
  every sure-fair-achievable `𝒟f`-trace has a [finite-branching / closed-reachable] witness
  ⟺ sure fairness never requires accumulating resolution.
That WLOG statement is the genuine remaining hardness — of the same difficulty as crux B. The
measure-theoretic disintegration route sidesteps continuity (it carries resolution as a kernel,
never re-evaluating `next` at a pointwise limit) but delivers *almost-sure* fairness, leaving the
sure-vs-a.s. gap as its residual.

**Subset-direction note.** Baking finite mass-splitting into `𝒟f` forces image-finite `sys` for the
Dirac lift anyway (`ω = μ.map PMF.pure` has support `{δ_{s'} : s' ∈ μ.support}`, finite iff
`μ.support` is). So image-finiteness is assumed on the subset side regardless — consistent with
Route B.

**Concrete next steps.**
1. Route B: bake finite mass-splitting into `𝒟f`, assume image-finite `sys`, add a
   `FinResolvedBranch` predicate (bounded transitions per `(ω.bind id).support`), discharge
   `lowerFairR_phantom_free` via `exists_infinite_chain`, and leave "the predicate is WLOG for sure
   fairness" as the one sorry.
2. Route A: keep `ReachBeliefsTight`, add a uniform `ω`-arity bound, and attack (iii) via measure-
   theoretic disintegration — accepting a.s. fairness plus a sure-vs-a.s. upgrade.
-/

/-! ### The minimal compactness input: tightness of the reachable beliefs -/

/-- **The compactness assumption crux B consumes.** Crux B threads *one* coherent infinite
belief-run out of the per-step coherence data by a relative-compactness argument over the belief
space `PMF State`. Its minimal analytic input is that the family of **reachable beliefs** — the
end-states `E.endState` of the `probOf`-positive belief-histories `E` of the forgotten execution
`PE'.average.distFToDist F` — is **tight**: for every `ε > 0` a *finite* set `T` of states carries
all but `ε` of every reachable belief's mass. By Prokhorov's theorem this is precisely relative
compactness of the reachable-belief family in the weak topology, so it is *the* compactness
hypothesis — not `[Fintype State]`, and not finiteness of the reachable state set. It is
`[Fintype State]`-free by design: `lowerFairR_reachBeliefsTight_of_fintype` discharges it under
`[Fintype State]` (take `T := Finset.univ`), while a genuine tightness condition on `sys` discharges
it with `State` infinite (unconditionally it would be *false* — beliefs may escape to infinity). -/
def ResolvedProbabilisticExecution.ReachBeliefsTight {sys : System State Label}
    (F : Fairness sys) (PE' : ResolvedProbabilisticExecution (sys.distF F)) : Prop :=
  ∀ ε : ENNReal, 0 < ε → ∃ T : Finset State,
    ∀ (E : AlterSeq (PMF State) Label) (hE : E.trans.Terminates),
      (PE'.average.distFToDist F).probOf E hE ≠ 0 →
        ∑' s : State, Set.indicator {s : State | s ∉ T} (⇑(E.endState hE)) s ≤ ε

/-! ### Crux B — phantom-freeness (consumes the tightness input, no finiteness) -/

/-- **Crux B: infinite consistent runs are fair.** Every infinite consistent concrete run `r` of the
μ-reading witness takes infinitely many `F`-fair steps. The `RCoherent` filter guarantees `r` lifts
to *one* coherent infinite `PE'`-belief-run, which is `PE'`-fair (`PE'.IsFair.inf_fair`), and the
fairness-revealing kernel `distFairHyperKernel` carries each `F.dist`-fair belief-step down to an
`F`-fair concrete step (`FairStepAt`). Extracting that single infinite belief-run from the per-step
coherence data is a relative-compactness (Prokhorov) argument over `PMF State`; its minimal input is
the tightness hypothesis `hT : PE'.ReachBeliefsTight F` — **not** `[Fintype State]`: the belief tree
branches over continuum-many `ν : PMF State` even when `sys` is image-finite, so `ImageFinite` does
not suffice and finite branching is never available. Tightness supplies relative compactness of
the belief family; the residual closedness of the coherence constraints (the scheduler need not be
continuous in the belief) stays inside this `sorry`. Left as a documented `sorry`. -/
theorem ResolvedProbabilisticExecution.lowerFairR_phantom_free {sys : System State Label}
    (F : Fairness sys) (PE' : ResolvedProbabilisticExecution (sys.distF F))
    (hT : PE'.ReachBeliefsTight F) (hfair : PE'.IsFair F.dist) (r : ResolvedExec State Label)
    (hinf : ¬ r.trans.Terminates) (hcons : (PE'.lowerFairR F).Consistent r) :
    ∀ N : ℕ, ∃ n : ℕ, N ≤ n ∧ F.FairStepAt r n := by
  sorry

/-- **`[Fintype State]` discharges the tightness input** — the crudest sufficient condition, and the
sole place finiteness need enter the development. With `State` finite every belief is supported
on `Finset.univ`, so `T := Finset.univ` leaves zero tail mass. Replacing `[Fintype State]` here with
a genuine tightness condition on `sys` discharges `ReachBeliefsTight` with `State` infinite. -/
theorem ResolvedProbabilisticExecution.lowerFairR_reachBeliefsTight_of_fintype
    {sys : System State Label} [Fintype State] (F : Fairness sys)
    (PE' : ResolvedProbabilisticExecution (sys.distF F)) : PE'.ReachBeliefsTight F := by
  intro ε _
  refine ⟨Finset.univ, fun E hE _ => ?_⟩
  have hempty : {s : State | s ∉ (Finset.univ : Finset State)} = ∅ := by ext s; simp
  rw [hempty]
  simp

/-! ### Assembling fairness of the witness -/

/-- **The μ-reading witness is sure-fair.** Combines the halt clause
(`lowerFairR_halt_fairDeadlock`) with phantom-freeness (`lowerFairR_phantom_free` = crux B), taking
the tightness input `hT : PE'.ReachBeliefsTight F` that crux B consumes. There is **no**
`[Fintype State]` here — finiteness, if it enters at all, does so only through whatever discharges
`hT` (e.g. `lowerFairR_reachBeliefsTight_of_fintype`). -/
theorem ResolvedProbabilisticExecution.lowerFairR_isFair {sys : System State Label}
    (F : Fairness sys) (PE' : ResolvedProbabilisticExecution (sys.distF F))
    (hT : PE'.ReachBeliefsTight F) (hfair : PE'.IsFair F.dist) :
    (PE'.lowerFairR F).IsFair F where
  halt_fairDeadlock := fun r h hcons h_none =>
    PE'.lowerFairR_halt_fairDeadlock F hfair r h hcons h_none
  inf_fair := fun r hinf hcons N => PE'.lowerFairR_phantom_free F hT hfair r hinf hcons N

/-! ### The superset theorem -/

/-- **Superset direction of the fair `𝒟f`-equivalence.** Every trace distribution achievable by a
fair resolved `𝒟f(sys,F)`-execution is achievable by a fair resolved `sys`-execution. Witnessed by
the μ-reading reconstruction `lowerFairR`: `lowerFairR_initState` (Dirac start),
`lowerFairR_isFair` (fairness, via cruxes) and `lowerFairR_traceProbR` (trace, crux A). **No
`[Fintype State]`**: the only compactness needed is the tightness hypothesis `hT` (one
`ReachBeliefsTight` per achieving execution), which crux B consumes; `..._of_fintype` below is the
finite-state corollary that discharges it. -/
theorem fairAchievableTraceDists_superset_distF {sys : System State Label} (F : Fairness sys)
    (hT : ∀ PE' : ResolvedProbabilisticExecution (sys.distF F), PE'.ReachBeliefsTight F) :
    fairAchievableTraceDists F.dist ⊆ fairAchievableTraceDists F := by
  rintro D ⟨PE', hinit, hfair, htp⟩
  exact ⟨PE'.lowerFairR F, PE'.lowerFairR_initState F hinit,
    PE'.lowerFairR_isFair F (hT PE') hfair,
    fun τ => (PE'.lowerFairR_traceProbR F hinit τ).trans (htp τ)⟩

/-- **Finite-state corollary.** Under `[Fintype State]` the tightness input is automatic
(`lowerFairR_reachBeliefsTight_of_fintype`), recovering the superset direction with finiteness
confined to that single discharge lemma. -/
theorem fairAchievableTraceDists_superset_distF_of_fintype {sys : System State Label}
    [Fintype State] (F : Fairness sys) :
    fairAchievableTraceDists F.dist ⊆ fairAchievableTraceDists F :=
  fairAchievableTraceDists_superset_distF F
    (fun PE' => PE'.lowerFairR_reachBeliefsTight_of_fintype F)

end PLTS
