/-
Copyright (c) 2026 Gaspard Reghem. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Gaspard Reghem
-/

import MyMathlibProject.Measure.Trajectory
import MyMathlibProject.Expansion.Trace
import MyMathlibProject.Simulation.Soundness

/-!
# The trace measure and measure-theoretic simulation soundness

This file pushes the trajectory measure `pe.trajMeasure` forward along the trace
map to a genuine probability measure `pe.traceMeasure` on `Seq Label`, and proves
the **cone lemma** `traceMeasure (cone labs) = traceProb (Seq.ofList labs)`. It then
lifts the existing finite-cone simulation soundness (`achievableTraceDists_subset`)
to the measure level: two probability measures on `Seq Label` that agree on all
cones are equal (π-system uniqueness), so the (already proven) equality of trace
distributions upgrades to equality of trace measures.

The trace map `trace'` is a genuinely measurable — but not cylinder-simple — map:
`trace'⁻¹(cone labs)` is the disjoint union of the cylinders of the tight
executions with trace `labs`, and proving `trace'` measurable *is* that partition,
which simultaneously yields the cone value.
-/

open MeasureTheory ProbabilityTheory Finset Stream'

-- The `Countable`/`Silent` instances are threaded as section variables but are
-- unused by many of the pure `Seq`/coordinate helpers; silence the over-inclusion
-- linter (matching the convention in `Simulation/Trace.lean`).
set_option linter.unusedSectionVars false

namespace PLTS

variable {State Label : Type} [Countable State] [Countable Label] [Silent Label]
  {sys : System State Label}

/-! ### The trace map and trace measure -/

open Classical in
/-- The live transitions of a trajectory `ω`: the maximal `some`-prefix of
`ω 1, ω 2, …`, truncated at the first `none`. A genuine `Seq`. -/
noncomputable def liveTrans (ω : Π n, TrajCoord State Label n) : Seq (Label × State) :=
  ⟨fun k => if (∀ j ≤ k, (ω (j + 1)).isSome) then ω (k + 1) else none, by
    intro n hn
    by_cases hg : ∀ j ≤ n + 1, (ω (j + 1)).isSome
    · exfalso
      have hgn : ∀ j ≤ n, (ω (j + 1)).isSome := fun j hj => hg j (Nat.le_succ_of_le hj)
      simp only [if_pos hgn] at hn
      have hs := hg n (Nat.le_succ n)
      rw [hn] at hs
      exact absurd hs (by simp)
    · simp only [if_neg hg]⟩

/-- The trace of a trajectory: the external labels of its live transitions.
Defined so that `trace' ω = System.trace sys ⟨ω 0, liveTrans ω⟩` (reusing the
existing `System.trace`). -/
noncomputable def trace' (ω : Π n, TrajCoord State Label n) : Seq Label :=
  ((liveTrans ω).filter (fun p => ¬ (p.1 = Silent.τ))).map Prod.fst

theorem trace'_eq (ω : Π n, TrajCoord State Label n) :
    trace' ω = System.trace sys ⟨ω 0, liveTrans ω⟩ := rfl

/-- The **cone** of a finite trace `labs`: all traces that extend it. -/
def cone (labs : List Label) : Set (Seq Label) :=
  {σ | ∀ k a, (Seq.ofList labs).get? k = some a → σ.get? k = some a}

/-- The trace σ-algebra on `Seq Label`, generated by cones. Scoped to avoid
imposing a σ-algebra on `Stream'.Seq` downstream. -/
scoped instance instMeasurableSpaceSeq : MeasurableSpace (Seq Label) :=
  MeasurableSpace.generateFrom (Set.range (cone (Label := Label)))

/-- Cones are measurable (they generate the σ-algebra). -/
theorem measurableSet_cone (labs : List Label) : MeasurableSet (cone labs) :=
  MeasurableSpace.measurableSet_generateFrom (Set.mem_range_self labs)

/-- The **trace measure** of a probabilistic execution: the pushforward of its
trajectory measure along the (measurable) trace map. -/
noncomputable def ProbabilisticExecution.traceMeasure (pe : ProbabilisticExecution sys) :
    Measure (Seq Label) := pe.trajMeasure.map trace'

/-- The set of trace measures achievable by a system from its Dirac initial state. -/
def achievableTraceMeasures (ls : System State Label) : Set (Measure (Seq Label)) :=
  {μ | ∃ pe : ProbabilisticExecution ls, pe.initState = PMF.pure ls.init ∧ μ = pe.traceMeasure}

/-- The cylinder in trajectory space determined by a finite execution `e`. -/
private noncomputable def Cyl (e : AlterSeq State Label) (hF : e.trans.Terminates) :
    Set (Π n, TrajCoord State Label n) :=
  cylinder (Finset.Iic (e.trans.length hF)) {tup e (e.trans.length hF)}

/-- Tight executions with a given external trace `labs`. Index set of the trace-cone partition. -/
abbrev TightTrace (sys : System State Label) (labs : List Label) : Type :=
  {e : AlterSeq State Label //
    e.trans.Terminates ∧ System.trace sys e = Seq.ofList labs ∧ System.IsTight sys e}

/-! ### The partition (crux) -/

theorem liveTrans_get? (ω : Π n, TrajCoord State Label n) (k : ℕ) :
    (liveTrans ω).get? k = if (∀ j ≤ k, (ω (j + 1)).isSome) then ω (k + 1) else none := rfl

theorem liveTrans_get?_eq_coord (ω : Π n, TrajCoord State Label n) (k : ℕ) (a : Label × State)
    (h : (liveTrans ω).get? k = some a) : ω (k + 1) = some a := by
  rw [liveTrans_get?] at h
  by_cases hg : ∀ j ≤ k, (ω (j + 1)).isSome
  · rwa [if_pos hg] at h
  · rw [if_neg hg] at h; exact absurd h (by simp)

/-- The coordinates of `ω` on the cylinder of `e` match those of `e`. -/
private theorem mem_Cyl_coord (e : AlterSeq State Label) (hF : e.trans.Terminates)
    {ω : Π n, TrajCoord State Label n} (hω : ω ∈ Cyl e hF)
    {m : ℕ} (hm : m ≤ e.trans.length hF) : ω m = coord e m := by
  have h_restr : (Finset.Iic (e.trans.length hF)).restrict ω = tup e (e.trans.length hF) := by
    have h := (MeasureTheory.mem_cylinder (Finset.Iic (e.trans.length hF))
      {tup e (e.trans.length hF)} ω).mp hω
    rwa [Set.mem_singleton_iff] at h
  exact congrFun h_restr ⟨m, Finset.mem_Iic.mpr hm⟩

/-- On the cylinder of `e`, `ω`'s initial coordinate is `e.init`. -/
private theorem mem_Cyl_init (e : AlterSeq State Label) (hF : e.trans.Terminates)
    {ω : Π n, TrajCoord State Label n} (hω : ω ∈ Cyl e hF) : ω 0 = e.init :=
  mem_Cyl_coord e hF hω (Nat.zero_le _)

/-- On the cylinder of `e`, `ω`'s transition coordinates match `e.trans`. -/
private theorem mem_Cyl_step (e : AlterSeq State Label) (hF : e.trans.Terminates)
    {ω : Π n, TrajCoord State Label n} (hω : ω ∈ Cyl e hF)
    {k : ℕ} (hk : k + 1 ≤ e.trans.length hF) : ω (k + 1) = e.trans.get? k :=
  mem_Cyl_coord e hF hω hk

/-- Conversely, matching all coordinates up to the length puts `ω` on the cylinder. -/
private theorem mem_Cyl_of_coord (e : AlterSeq State Label) (hF : e.trans.Terminates)
    {ω : Π n, TrajCoord State Label n}
    (h : ∀ m ≤ e.trans.length hF, ω m = coord e m) : ω ∈ Cyl e hF := by
  unfold Cyl
  rw [MeasureTheory.mem_cylinder, Set.mem_singleton_iff]
  funext i
  obtain ⟨m, hm⟩ := i
  exact h m (Finset.mem_Iic.mp hm)

/-- **L2.** On the cylinder of `e`, the live transitions extend `e.trans`. -/
theorem liveTrans_eq_append (e : AlterSeq State Label) (hF : e.trans.Terminates)
    (ω : Π n, TrajCoord State Label n) (hω : ω ∈ Cyl e hF) :
    liveTrans ω = e.trans.append ((liveTrans ω).drop (e.trans.length hF)) := by
  have h_min : ∀ k < e.trans.length hF, ¬ e.trans.TerminatedAt k := by
    intro k hk hT
    have hlen : e.trans.length hF ≤ k := Seq.length_le_iff.mpr hT
    omega
  have h_done : e.trans.TerminatedAt (e.trans.length hF) := Seq.length_le_iff.mp le_rfl
  apply Seq.ext
  intro n
  by_cases hn : e.trans.TerminatedAt n
  · have hLn : e.trans.length hF ≤ n := Seq.length_le_iff.mpr hn
    obtain ⟨d, rfl⟩ : ∃ d, n = e.trans.length hF + d := ⟨n - e.trans.length hF, by omega⟩
    rw [Seq.get?_append_after_length h_min h_done d, Seq.drop_get?]
  · have hnL : n < e.trans.length hF := by
      by_contra hc; exact hn (Seq.length_le_iff.mp (Nat.not_lt.mp hc))
    rw [Seq.get?_append_before_length hn, liveTrans_get?]
    have hguard : ∀ j ≤ n, (ω (j + 1)).isSome := by
      intro j hj
      rw [mem_Cyl_step e hF hω (by omega : j + 1 ≤ e.trans.length hF)]
      cases hget : e.trans.get? j with
      | none => exact absurd hget (h_min j (by omega))
      | some v => rfl
    rw [if_pos hguard, mem_Cyl_step e hF hω (by omega : n + 1 ≤ e.trans.length hF)]

/-- **L3 (covering).** The cylinder of a tight execution sits inside the cone preimage. -/
theorem Cyl_subset_preimage_cone (e : AlterSeq State Label) (hF : e.trans.Terminates)
    (labs : List Label) (htr : System.trace sys e = Seq.ofList labs) :
    Cyl e hF ⊆ trace' ⁻¹' cone labs := by
  intro ω hω k a hka
  have h2 : liveTrans ω = e.trans.append ((liveTrans ω).drop (e.trans.length hF)) :=
    liveTrans_eq_append e hF ω hω
  obtain ⟨t, hgt⟩ : ∃ t, (liveTrans ω).drop (e.trans.length hF) = t := ⟨_, rfl⟩
  rw [hgt] at h2
  have hcalc : trace' ω = (Seq.ofList labs).append
      ((t.filter (fun p => ¬ (p.1 = Silent.τ))).map Prod.fst) := by
    unfold trace'
    rw [h2, Seq.filter_append _ e.trans t hF, Seq.map_append,
      show Seq.map Prod.fst (Seq.filter (fun p => ¬ (p.1 = Silent.τ)) e.trans)
        = Seq.ofList labs from htr]
  have hnt : ¬ (Seq.ofList labs).TerminatedAt k := by
    change ¬ ((Seq.ofList labs).get? k = none)
    rw [hka]; exact Option.some_ne_none a
  rw [hcalc, Seq.get?_append_before_length hnt]
  exact hka

/-- The trace ignores a leading internal transition. -/
private theorem trace_cons_internal (i s' : State) (l : Label) (rest : Seq (Label × State))
    (h : l = Silent.τ) :
    sys.trace (⟨i, Seq.cons (l, s') rest⟩ : AlterSeq State Label)
      = sys.trace (⟨i, rest⟩ : AlterSeq State Label) := by
  unfold System.trace
  rw [Seq.filter_cons_neg (l, s') rest (not_not.mpr h)]

/-- The trace of an all-internal transition list is empty. -/
private theorem trace_ofList_all_internal (i : State) :
    ∀ (L : List (Label × State)), (∀ p ∈ L, p.1 = Silent.τ) →
      sys.trace (⟨i, Seq.ofList L⟩ : AlterSeq State Label) = Seq.nil := by
  intro L
  induction L with
  | nil => intro _; rw [Seq.ofList_nil]; exact System.trace_init sys i
  | cons a L ih =>
    intro hall
    obtain ⟨l, s'⟩ := a
    rw [Seq.ofList_cons, trace_cons_internal i s' l (Seq.ofList L)
      (hall (l, s') (List.mem_cons.mpr (Or.inl rfl)))]
    exact ih (fun p hp => hall p (List.mem_cons.mpr (Or.inr hp)))

/-- If the filtered sequence has a head, that head is a genuine element of the source
satisfying the predicate. -/
private theorem filter_get?_zero {α : Type} (P : α → Prop) (s : Seq α) {x : α}
    (h : (s.filter P).get? 0 = some x) : ∃ n, s.get? n = some x ∧ P x := by
  classical
  by_cases hex : ∃ n, ∃ a, s.get? n = some a ∧ P a
  · have hspec := (Nat.find_spec hex).choose_spec
    have hcons : s.filter P = Stream'.Seq.cons (Nat.find_spec hex).choose
        ((s.drop (Nat.find hex + 1)).filter P) := by
      unfold Stream'.Seq.filter
      apply Stream'.Seq.corec_cons
      exact dif_pos hex
    rw [hcons, Seq.get?_cons_zero] at h
    have hx : (Nat.find_spec hex).choose = x := Option.some_inj.mp h
    exact ⟨Nat.find hex, hx ▸ hspec.1, hx ▸ hspec.2⟩
  · exfalso
    have hnil : s.filter P = Stream'.Seq.nil := by
      unfold Stream'.Seq.filter
      apply Stream'.Seq.corec_nil
      exact dif_neg hex
    rw [hnil] at h
    simp at h

/-- If `A` terminates and `A = A.append B`, then `B` is empty. -/
private theorem append_eq_self_left {α : Type} (A B : Seq α) (hA : A.Terminates)
    (h : A = A.append B) : B = Stream'.Seq.nil := by
  have hb0 : B.get? 0 = none := by
    have h1 : A.get? (Nat.find hA) = none := Nat.find_spec hA
    have h2 : (A.append B).get? (Nat.find hA + 0) = B.get? 0 := Seq.get?_append_find hA B 0
    rw [Nat.add_zero, ← h, h1] at h2
    exact h2.symm
  exact Stream'.Seq.terminatedAt_zero_iff.mp hb0

/-- Dropping past a termination point yields the empty sequence. -/
private theorem drop_eq_nil_of_terminatedAt {α : Type} (s : Seq α) {n : ℕ}
    (h : s.TerminatedAt n) : s.drop n = Stream'.Seq.nil := by
  apply Seq.ext
  intro k
  rw [Seq.drop_get?, Stream'.Seq.get?_nil]
  exact Seq.le_stable s (Nat.le_add_right n k) h

/-- A `P`-satisfying element makes the filtered sequence non-empty at position `0`. -/
private theorem filter_ne_nil_of_get? {α : Type} (P : α → Prop) (s : Seq α) {m : ℕ} {x : α}
    (hget : s.get? m = some x) (hP : P x) : (s.filter P).get? 0 ≠ none := by
  classical
  have hex : ∃ n, ∃ a, s.get? n = some a ∧ P a := ⟨m, x, hget, hP⟩
  have hcons : s.filter P = Stream'.Seq.cons (Nat.find_spec hex).choose
      ((s.drop (Nat.find hex + 1)).filter P) := by
    unfold Stream'.Seq.filter
    apply Stream'.Seq.corec_cons
    exact dif_pos hex
  rw [hcons, Seq.get?_cons_zero]
  exact Option.some_ne_none _

/-- **L4 auxiliary.** Two tight executions with the same trace that share a trajectory, the
shorter one first, are equal. -/
private theorem tightTrace_eq_of_le {labs : List Label} (e₁ e₂ : TightTrace sys labs)
    (ω : Π n, TrajCoord State Label n)
    (hω1 : ω ∈ Cyl e₁.1 e₁.2.1) (hω2 : ω ∈ Cyl e₂.1 e₂.2.1)
    (hle : e₁.1.trans.length e₁.2.1 ≤ e₂.1.trans.length e₂.2.1) :
    e₁ = e₂ := by
  have hinit : e₁.1.init = e₂.1.init :=
    (mem_Cyl_init e₁.1 e₁.2.1 hω1).symm.trans (mem_Cyl_init e₂.1 e₂.2.1 hω2)
  have h_min₁ : ∀ k < e₁.1.trans.length e₁.2.1, ¬ e₁.1.trans.TerminatedAt k := by
    intro k hk hT
    have hlk : e₁.1.trans.length e₁.2.1 ≤ k := Seq.length_le_iff.mpr hT
    omega
  -- `t₂` extends `t₁`.
  have hsplit : e₂.1.trans
      = e₁.1.trans.append (e₂.1.trans.drop (e₁.1.trans.length e₁.2.1)) := by
    apply Seq.ext
    intro n
    by_cases hn : e₁.1.trans.TerminatedAt n
    · have hLn : e₁.1.trans.length e₁.2.1 ≤ n := Seq.length_le_iff.mpr hn
      obtain ⟨d, rfl⟩ : ∃ d, n = e₁.1.trans.length e₁.2.1 + d :=
        ⟨n - e₁.1.trans.length e₁.2.1, by omega⟩
      rw [Seq.get?_append_after_length h_min₁ (Seq.length_le_iff.mp le_rfl) d, Seq.drop_get?]
    · have hnL : n < e₁.1.trans.length e₁.2.1 := by
        by_contra hc; exact hn (Seq.length_le_iff.mp (Nat.not_lt.mp hc))
      rw [Seq.get?_append_before_length hn,
        ← mem_Cyl_step e₁.1 e₁.2.1 hω1 (by omega : n + 1 ≤ e₁.1.trans.length e₁.2.1),
        ← mem_Cyl_step e₂.1 e₂.2.1 hω2 (by omega : n + 1 ≤ e₂.1.trans.length e₂.2.1)]
  -- The extending tail has empty trace.
  have htail_nil : System.trace sys
      (⟨e₂.1.init, e₂.1.trans.drop (e₁.1.trans.length e₁.2.1)⟩ : AlterSeq State Label)
      = Seq.nil := by
    have happ : System.trace sys e₂.1
        = (Seq.ofList labs).append (System.trace sys
            (⟨e₂.1.init, e₂.1.trans.drop (e₁.1.trans.length e₁.2.1)⟩ : AlterSeq State Label)) := by
      conv_lhs => rw [show e₂.1 = (⟨e₂.1.init, e₂.1.trans⟩ : AlterSeq State Label) from rfl, hsplit]
      rw [trace_append e₂.1.init e₁.1.trans _ e₁.2.1,
        show System.trace sys (⟨e₂.1.init, e₁.1.trans⟩ : AlterSeq State Label)
          = Seq.ofList labs from e₁.2.2.1]
    rw [show System.trace sys e₂.1 = Seq.ofList labs from e₂.2.2.1] at happ
    exact append_eq_self_left (Seq.ofList labs) _ (Seq.terminates_ofList labs) happ
  -- Hence `t₂` is no longer than `t₁`.
  have hL2le : e₂.1.trans.length e₂.2.1 ≤ e₁.1.trans.length e₁.2.1 := by
    by_contra hlt
    have hlt' : e₁.1.trans.length e₁.2.1 < e₂.1.trans.length e₂.2.1 := Nat.lt_of_not_le hlt
    rcases e₂.2.2.2 with h0 | ⟨n, l, s, hgn, htn, hext⟩
    · have : e₂.1.trans.length e₂.2.1 ≤ 0 := Seq.length_le_iff.mpr h0
      omega
    · have hn_not : ¬ e₂.1.trans.TerminatedAt n := by
        rw [Stream'.Seq.TerminatedAt, hgn]; exact Option.some_ne_none _
      have hn_lt : n < e₂.1.trans.length e₂.2.1 := by
        by_contra hc; exact hn_not (Seq.length_le_iff.mp (Nat.not_lt.mp hc))
      have hlen_le : e₂.1.trans.length e₂.2.1 ≤ n + 1 := Seq.length_le_iff.mpr htn
      -- position `n` lies in the tail
      have hn_ge : e₁.1.trans.length e₁.2.1 ≤ n := by omega
      have heq : e₁.1.trans.length e₁.2.1 + (n - e₁.1.trans.length e₁.2.1) = n := by omega
      have htail_get : (e₂.1.trans.drop (e₁.1.trans.length e₁.2.1)).get?
          (n - e₁.1.trans.length e₁.2.1) = some (l, s) := by
        rw [Seq.drop_get?, heq]; exact hgn
      have hfne := filter_ne_nil_of_get? (fun p => ¬ (p.1 = Silent.τ)) _ htail_get hext
      -- but the tail's trace is nil, so the filtered head is `none`
      have hmap : ((e₂.1.trans.drop (e₁.1.trans.length e₁.2.1)).filter
          (fun p => ¬ (p.1 = Silent.τ))).map Prod.fst = Seq.nil := htail_nil
      obtain ⟨z, hz⟩ := Option.ne_none_iff_exists'.mp hfne
      have hcontra : (((e₂.1.trans.drop (e₁.1.trans.length e₁.2.1)).filter
          (fun p => ¬ (p.1 = Silent.τ))).map Prod.fst).get? 0 = some z.1 := by
        rw [Seq.map_get?, hz]; rfl
      rw [hmap, Stream'.Seq.get?_nil] at hcontra
      exact absurd hcontra.symm (Option.some_ne_none _)
  -- Conclude.
  apply Subtype.ext
  have htrans : e₁.1.trans = e₂.1.trans := by
    rw [hsplit, drop_eq_nil_of_terminatedAt _ (Seq.length_le_iff.mp hL2le), Seq.append_nil]
  rw [show e₁.1 = (⟨e₁.1.init, e₁.1.trans⟩ : AlterSeq State Label) from rfl, hinit, htrans]

/-- **L4 (disjointness).** Distinct tight executions with the same trace have disjoint cylinders. -/
theorem Cyl_disjoint {labs : List Label} (e₁ e₂ : TightTrace sys labs) (hne : e₁ ≠ e₂) :
    Disjoint (Cyl e₁.1 e₁.2.1) (Cyl e₂.1 e₂.2.1) := by
  rw [Set.disjoint_left]
  intro ω hω1 hω2
  apply hne
  rcases le_total (e₁.1.trans.length e₁.2.1) (e₂.1.trans.length e₂.2.1) with hle | hle
  · exact tightTrace_eq_of_le e₁ e₂ ω hω1 hω2 hle
  · exact (tightTrace_eq_of_le e₂ e₁ ω hω2 hω1 hle).symm

/-- Auxiliary for L5, phrased with the first-external position `n` explicit so it can
be proved by induction on `n`. -/
private theorem firstExt_split_aux :
    ∀ (n : ℕ) (S : Seq (Label × State)) (x : Label × State),
      S.get? n = some x → ¬ (x.1 = Silent.τ) →
      (∀ m < n, ∃ a, S.get? m = some a ∧ a.1 = Silent.τ) →
      ∃ (pre : List (Label × State)) (S' : Seq (Label × State)),
        (∀ p ∈ pre, p.1 = Silent.τ) ∧
        S = (Seq.ofList pre).append (Seq.cons x S') := by
  intro n
  induction n with
  | zero =>
    intro S x hx _ _
    refine ⟨[], S.tail, by simp, ?_⟩
    rw [Seq.ofList_nil, Seq.nil_append]
    exact Seq.head_eq_some hx
  | succ k ih =>
    intro S x hx hext hall
    obtain ⟨a₀, hget0, hint0⟩ := hall 0 (Nat.succ_pos k)
    have hScons : S = Seq.cons a₀ S.tail := Seq.head_eq_some hget0
    have hx' : S.tail.get? k = some x := by rw [Seq.get?_tail]; exact hx
    have hall' : ∀ m < k, ∃ a, S.tail.get? m = some a ∧ a.1 = Silent.τ := by
      intro m hm
      obtain ⟨a, hga, hia⟩ := hall (m + 1) (by omega)
      exact ⟨a, by rw [Seq.get?_tail]; exact hga, hia⟩
    obtain ⟨pre', S', hpre', hsplit'⟩ := ih S.tail x hx' hext hall'
    refine ⟨a₀ :: pre', S', ?_, ?_⟩
    · intro p hp
      rcases List.mem_cons.mp hp with rfl | hp'
      · exact hint0
      · exact hpre' p hp'
    · rw [hScons, hsplit', Seq.ofList_cons, Seq.cons_append]

/-- **L5.** Split a `Seq` at its first external transition. -/
theorem exists_firstExt_split (S : Seq (Label × State))
    (h : ∃ n a, S.get? n = some a ∧ ¬ (a.1 = Silent.τ)) :
    ∃ (pre : List (Label × State)) (x : Label × State) (S' : Seq (Label × State)),
      (∀ p ∈ pre, p.1 = Silent.τ) ∧ ¬ (x.1 = Silent.τ) ∧
      S = (Seq.ofList pre).append (Seq.cons x S') := by
  classical
  obtain ⟨N, aN, hgaN, hiaN⟩ := h
  have hP_ex : ∃ n, ∃ a, S.get? n = some a ∧ ¬ (a.1 = Silent.τ) := ⟨N, aN, hgaN, hiaN⟩
  obtain ⟨x, hxget, hxext⟩ := Nat.find_spec hP_ex
  have hall : ∀ m < Nat.find hP_ex, ∃ a, S.get? m = some a ∧ a.1 = Silent.τ := by
    intro m hm
    have hnP := Nat.find_min hP_ex hm
    have hne : S.get? m ≠ none := by
      intro hnone
      have hn0 : S.get? (Nat.find hP_ex) = none := Seq.le_stable S (le_of_lt hm) hnone
      rw [hxget] at hn0; exact Option.some_ne_none x hn0
    obtain ⟨a, hga⟩ := Option.ne_none_iff_exists'.mp hne
    refine ⟨a, hga, ?_⟩
    by_contra hia
    exact hnP ⟨a, hga, hia⟩
  obtain ⟨pre, S', hpre, hsplit⟩ := firstExt_split_aux (Nat.find hP_ex) S x hxget hxext hall
  exact ⟨pre, x, S', hpre, hxext, hsplit⟩

/-- Tightness of a list-execution: either empty, or its last label is external. -/
private theorem isTight_ofList_iff (i : State) (L : List (Label × State)) :
    System.IsTight sys (⟨i, Seq.ofList L⟩ : AlterSeq State Label) ↔
      ∀ p, L.getLast? = some p → ¬ (p.1 = Silent.τ) := by
  have hget : ∀ m, (Seq.ofList L).get? m = L[m]? := fun m => Seq.ofList_get? L m
  have hterm : ∀ m, (Seq.ofList L).TerminatedAt m ↔ L.length ≤ m := by
    intro m
    change (Seq.ofList L).get? m = none ↔ L.length ≤ m
    rw [hget m, List.getElem?_eq_none_iff]
  unfold System.IsTight
  constructor
  · rintro (h0 | ⟨n, l', s', hgn, htn, hext⟩) p hp
    · rw [hterm] at h0
      cases L with
      | nil => simp at hp
      | cons a t => simp at h0
    · rw [hget] at hgn
      rw [hterm] at htn
      have hn_lt : n < L.length := by
        by_contra hc
        rw [List.getElem?_eq_none_iff.mpr (Nat.le_of_not_lt hc)] at hgn
        simp at hgn
      have hlen : L.length = n + 1 := le_antisymm htn hn_lt
      rw [List.getLast?_eq_getElem?, hlen] at hp
      simp only [Nat.add_sub_cancel] at hp
      rw [hgn] at hp
      obtain rfl : (l', s') = p := Option.some_inj.mp hp
      exact hext
  · intro hlast
    cases hL : L.getLast? with
    | none =>
      left
      rw [hterm, List.getLast?_eq_none_iff.mp hL]; simp
    | some p =>
      obtain ⟨pl, ps⟩ := p
      right
      have hne : L ≠ [] := by intro h; rw [h] at hL; simp at hL
      have hlen_pos : 0 < L.length := List.length_pos_of_ne_nil hne
      refine ⟨L.length - 1, pl, ps, ?_, ?_, ?_⟩
      · rw [hget, ← List.getLast?_eq_getElem?, hL]
      · rw [hterm]; omega
      · exact hlast (pl, ps) hL

/-- **L6 (construction).** From a live-transition `Seq` whose trace extends `labs`,
extract the tight prefix realising `labs`. -/
theorem exists_tightPrefix (labs : List Label) (i : State) (S : Seq (Label × State))
    (hpre : ∀ k a, (Seq.ofList labs).get? k = some a →
      ((S.filter (fun p => ¬ (p.1 = Silent.τ))).map Prod.fst).get? k = some a) :
    ∃ (P : List (Label × State)) (S' : Seq (Label × State)),
      S = (Seq.ofList P).append S' ∧
      System.trace sys (⟨i, Seq.ofList P⟩ : AlterSeq State Label) = Seq.ofList labs ∧
      System.IsTight sys (⟨i, Seq.ofList P⟩ : AlterSeq State Label) := by
  induction labs generalizing S with
  | nil =>
    refine ⟨[], S, ?_, ?_, ?_⟩
    · rw [Seq.ofList_nil, Seq.nil_append]
    · rw [Seq.ofList_nil]; exact System.trace_init sys i
    · rw [isTight_ofList_iff]; intro p hp; simp at hp
  | cons a rest ih =>
    have h0 : (System.trace sys (⟨i, S⟩ : AlterSeq State Label)).get? 0 = some a :=
      hpre 0 a (by rw [Seq.ofList_cons, Seq.get?_cons_zero])
    have hexist : ∃ n a', S.get? n = some a' ∧ ¬ (a'.1 = Silent.τ) := by
      have h0' := h0
      change ((S.filter (fun p => ¬ (p.1 = Silent.τ))).map Prod.fst).get? 0 = some a at h0'
      rw [Seq.map_get?] at h0'
      cases hf : (S.filter (fun p => ¬ (p.1 = Silent.τ))).get? 0 with
      | none => rw [hf] at h0'; simp at h0'
      | some y =>
        obtain ⟨n, hSn, hPy⟩ := filter_get?_zero _ S hf
        exact ⟨n, y, hSn, hPy⟩
    obtain ⟨pre, xz, S', hpre_int, hxz_ext, hSsplit⟩ := exists_firstExt_split S hexist
    obtain ⟨l, s'⟩ := xz
    have htrace_eq : System.trace sys (⟨i, S⟩ : AlterSeq State Label)
        = Seq.cons l (System.trace sys (⟨s', S'⟩ : AlterSeq State Label)) := by
      rw [hSsplit, trace_append i (Seq.ofList pre) (Seq.cons (l, s') S')
        (Seq.terminates_ofList pre), trace_ofList_all_internal i pre hpre_int,
        System.trace_cons_external sys i l s' S' hxz_ext, Seq.nil_append]
    have hla : l = a := by
      rw [htrace_eq, Seq.get?_cons_zero] at h0
      exact Option.some_inj.mp h0
    subst hla
    have hpre' : ∀ k a', (Seq.ofList rest).get? k = some a' →
        ((S'.filter (fun p => ¬ (p.1 = Silent.τ))).map Prod.fst).get? k = some a' := by
      intro k a' hk
      have hk1 : (Seq.ofList (l :: rest)).get? (k + 1) = some a' := by
        rw [Seq.ofList_cons, Seq.get?_cons_succ]; exact hk
      have hcall := hpre (k + 1) a' hk1
      change (System.trace sys (⟨i, S⟩ : AlterSeq State Label)).get? (k + 1) = some a' at hcall
      rw [htrace_eq, Seq.get?_cons_succ] at hcall
      exact hcall
    obtain ⟨P', S'', hsplit', htr', htight'⟩ := ih S' hpre'
    refine ⟨pre ++ (l, s') :: P', S'', ?_, ?_, ?_⟩
    · rw [hSsplit, hsplit', Seq.ofList_append, Seq.ofList_cons, Seq.append_assoc, Seq.cons_append]
    · rw [Seq.ofList_append, Seq.ofList_cons,
        trace_append i (Seq.ofList pre) _ (Seq.terminates_ofList pre),
        trace_ofList_all_internal i pre hpre_int,
        System.trace_cons_external sys i l s' (Seq.ofList P') hxz_ext, Seq.nil_append,
        Seq.ofList_cons,
        show System.trace sys (⟨s', Seq.ofList P'⟩ : AlterSeq State Label)
          = Seq.ofList rest from htr']
    · rw [isTight_ofList_iff] at htight' ⊢
      intro p hp
      rw [List.getLast?_append_cons, List.getLast?_cons] at hp
      obtain rfl := Option.some_inj.mp hp
      cases hq : P'.getLast? with
      | none => simp only [Option.getD_none]; exact hxz_ext
      | some q => simp only [Option.getD_some]; exact htight' q hq

/-- **L7.** The cone preimage is covered by the tight-execution cylinders. -/
theorem preimage_cone_subset_iUnion (labs : List Label) :
    trace' ⁻¹' cone labs ⊆ ⋃ e : TightTrace sys labs, Cyl e.1 e.2.1 := by
  intro ω hω
  have hpre : ∀ k a, (Seq.ofList labs).get? k = some a →
      (((liveTrans ω).filter (fun p => ¬ (p.1 = Silent.τ))).map Prod.fst).get? k = some a := hω
  obtain ⟨P, S', hSsplit, htr, htight⟩ :=
    exists_tightPrefix (State := State) labs (ω 0) (liveTrans ω) hpre
  have hF : (Seq.ofList P).Terminates := Seq.terminates_ofList P
  have hmemCyl : ω ∈ Cyl (⟨ω 0, Seq.ofList P⟩ : AlterSeq State Label) hF := by
    apply mem_Cyl_of_coord
    intro m hm
    cases m with
    | zero => rfl
    | succ k =>
      change k + 1 ≤ (Seq.ofList P).length hF at hm
      have hnt : ¬ (Seq.ofList P).TerminatedAt k := by
        intro hT
        have hlk : (Seq.ofList P).length hF ≤ k := Seq.length_le_iff.mpr hT
        omega
      obtain ⟨a, ha⟩ : ∃ a, (Seq.ofList P).get? k = some a := by
        cases hg : (Seq.ofList P).get? k with
        | none => exact absurd hg hnt
        | some a => exact ⟨a, rfl⟩
      have hlv : (liveTrans ω).get? k = some a := by
        rw [hSsplit, Seq.get?_append_before_length hnt, ha]
      rw [liveTrans_get?_eq_coord ω k a hlv]
      exact ha.symm
  exact Set.mem_iUnion.mpr ⟨⟨⟨ω 0, Seq.ofList P⟩, hF, htr, htight⟩, hmemCyl⟩

/-- **L8 (partition).** The cone preimage is exactly the disjoint union of tight cylinders. -/
theorem trace'_preimage_cone_eq (labs : List Label) :
    trace' ⁻¹' cone labs = ⋃ e : TightTrace sys labs, Cyl e.1 e.2.1 := by
  apply Set.Subset.antisymm (preimage_cone_subset_iUnion labs)
  apply Set.iUnion_subset
  intro e
  exact Cyl_subset_preimage_cone e.1 e.2.1 labs e.2.2.1

instance instCountableTightTrace (labs : List Label) : Countable (TightTrace sys labs) := by
  apply Function.Injective.countable
    (f := fun e : TightTrace sys labs => (e.1.init, e.1.trans.toList e.2.1))
  intro e₁ e₂ heq
  apply Subtype.ext
  have hi : e₁.1.init = e₂.1.init := congrArg Prod.fst heq
  have ht : e₁.1.trans.toList e₁.2.1 = e₂.1.trans.toList e₂.2.1 := congrArg Prod.snd heq
  have htrans : e₁.1.trans = e₂.1.trans := by
    rw [← Seq.ofList_toList e₁.1.trans e₁.2.1, ht, Seq.ofList_toList e₂.1.trans e₂.2.1]
  rw [show e₁.1 = (⟨e₁.1.init, e₁.1.trans⟩ : AlterSeq State Label) from rfl, hi, htrans]

include sys in
theorem measurable_trace' :
    Measurable (trace' : (Π n, TrajCoord State Label n) → Seq Label) := by
  apply measurable_generateFrom
  rintro t ⟨labs, rfl⟩
  rw [trace'_preimage_cone_eq (sys := sys) labs]
  apply MeasurableSet.iUnion
  intro e
  unfold Cyl
  exact MeasurableSet.cylinder _ (measurableSet_singleton _)

/-! ### The cone lemma (Stage-1 deliverable) -/

/-- **The cone lemma.** The trace measure of a cone equals the finite-cone trace probability. -/
theorem ProbabilisticExecution.traceMeasure_cone (pe : ProbabilisticExecution sys)
    (labs : List Label) :
    pe.traceMeasure (cone labs) = sys.traceProb pe (Seq.ofList labs) := by
  rw [ProbabilisticExecution.traceMeasure,
    Measure.map_apply (measurable_trace' (sys := sys))
      (MeasurableSpace.measurableSet_generateFrom ⟨labs, rfl⟩),
    trace'_preimage_cone_eq (sys := sys),
    measure_iUnion (fun e₁ e₂ hne => Cyl_disjoint e₁ e₂ hne)
      (fun e => by unfold Cyl; exact MeasurableSet.cylinder _ (measurableSet_singleton _))]
  unfold System.traceProb
  apply tsum_congr
  intro e
  exact pe.trajMeasure_cylinder e.1 e.2.1

instance (pe : ProbabilisticExecution sys) : IsProbabilityMeasure pe.traceMeasure := by
  rw [ProbabilisticExecution.traceMeasure]
  exact Measure.isProbabilityMeasure_map (measurable_trace' (sys := sys)).aemeasurable

/-! ### Stage 2: uniqueness, generic lift, corollaries -/

theorem cone_nil : cone ([] : List Label) = Set.univ := by
  ext σ
  simp only [cone, Set.mem_setOf_eq, Set.mem_univ, iff_true]
  intro k a h
  rw [Seq.ofList_get?] at h
  simp at h

/-- If `a` is a prefix of `b` (their `get?`s agree where `a` is defined), then the
larger cone is contained in the smaller. -/
private theorem cone_subset_cone_of_agree {a b : List Label}
    (hagree : ∀ k v, (Seq.ofList a).get? k = some v → (Seq.ofList b).get? k = some v) :
    cone b ⊆ cone a := fun _ hτ k v hk => hτ k v (hagree k v hk)

/-- Two cones with a common element are `get?`-compatible on the shorter list. -/
private theorem ofList_get?_agree {a b : List Label} {σ : Seq Label}
    (hσa : σ ∈ cone a) (hσb : σ ∈ cone b) (hab : a.length ≤ b.length)
    (k : ℕ) (v : Label) (hk : (Seq.ofList a).get? k = some v) :
    (Seq.ofList b).get? k = some v := by
  have h1 : σ.get? k = some v := hσa k v hk
  have hka : k < a.length := by
    by_contra hc
    rw [Seq.ofList_get?, List.getElem?_eq_none_iff.mpr (Nat.not_lt.mp hc)] at hk
    exact absurd hk (by simp)
  have hkb : k < b.length := lt_of_lt_of_le hka hab
  obtain ⟨w, hw⟩ : ∃ w, (Seq.ofList b).get? k = some w :=
    ⟨b[k], by rw [Seq.ofList_get?]; exact List.getElem?_eq_getElem hkb⟩
  have h2 : σ.get? k = some w := hσb k w hw
  rw [hw]; exact h2.symm.trans h1

theorem isPiSystem_range_cone : IsPiSystem (Set.range (cone (Label := Label))) := by
  rintro _ ⟨a, rfl⟩ _ ⟨b, rfl⟩ ⟨σ, hσa, hσb⟩
  rcases le_total a.length b.length with hab | hba
  · exact ⟨b, (Set.inter_eq_right.mpr
      (cone_subset_cone_of_agree (ofList_get?_agree hσa hσb hab))).symm⟩
  · exact ⟨a, (Set.inter_eq_left.mpr
      (cone_subset_cone_of_agree (ofList_get?_agree hσb hσa hba))).symm⟩

/-- **Uniqueness.** Two finite measures on `Seq Label` agreeing on every cone are equal. -/
theorem traceMeasure_ext {μ ν : Measure (Seq Label)} [IsFiniteMeasure μ]
    (h : ∀ labs, μ (cone labs) = ν (cone labs)) : μ = ν := by
  refine MeasureTheory.ext_of_generate_finite (Set.range (cone (Label := Label))) rfl
    isPiSystem_range_cone (fun s hs => ?_) ?_
  · obtain ⟨labs, rfl⟩ := hs; exact h labs
  · rw [← cone_nil]; exact h []

variable {State_C State_A : Type} [Countable State_C] [Countable State_A]

/-- **Generic lift.** If two systems have the same achievable trace distributions inclusion,
they have the same achievable trace measures inclusion. -/
theorem achievableTraceMeasures_subset_of_traceDists
    {sys_C : System State_C Label} {sys_A : System State_A Label}
    (h : achievableTraceDists sys_C ⊆ achievableTraceDists sys_A) :
    achievableTraceMeasures sys_C ⊆ achievableTraceMeasures sys_A := by
  rintro _ ⟨pe_C, hinit_C, rfl⟩
  have hD : (fun τ => sys_C.traceProb pe_C τ) ∈ achievableTraceDists sys_C :=
    ⟨pe_C, hinit_C, fun _ => rfl⟩
  obtain ⟨pe_A, hinit_A, hpe_A⟩ := h hD
  refine ⟨pe_A, hinit_A, ?_⟩
  apply traceMeasure_ext
  intro labs
  rw [pe_C.traceMeasure_cone, pe_A.traceMeasure_cone, hpe_A (Seq.ofList labs)]

/-- **Measure-theoretic soundness of forward simulation.** -/
theorem ProbabilisticForwardSimulation.achievableTraceMeasures_subset
    {sys_C : System State_C Label} {sys_A : System State_A Label}
    {R : State_C → PMF State_A → Prop}
    (sim : ProbabilisticForwardSimulation sys_C sys_A R) :
    achievableTraceMeasures sys_C ⊆ achievableTraceMeasures sys_A :=
  achievableTraceMeasures_subset_of_traceDists sim.achievableTraceDists_subset

/-- **Measure-theoretic soundness of weak simulation.** -/
theorem WeakProbabilisticSimulation.achievableTraceMeasures_subset
    {sys_C : System State_C Label} {sys_A : System State_A Label}
    {R : State_C → State_A → Prop}
    (sim : WeakProbabilisticSimulation sys_C sys_A R) :
    achievableTraceMeasures sys_C ⊆ achievableTraceMeasures sys_A :=
  achievableTraceMeasures_subset_of_traceDists sim.achievableTraceDists_subset

/-- **Measure-theoretic soundness of strong simulation.** -/
theorem StrongProbabilisticSimulation.achievableTraceMeasures_subset
    {sys_C : System State_C Label} {sys_A : System State_A Label}
    {R : State_C → State_A → Prop}
    (sim : StrongProbabilisticSimulation sys_C sys_A R) :
    achievableTraceMeasures sys_C ⊆ achievableTraceMeasures sys_A :=
  achievableTraceMeasures_subset_of_traceDists sim.achievableTraceDists_subset

end PLTS
