/-
Copyright (c) 2026 Gaspard Reghem. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Gaspard Reghem
-/

import MyMathlibProject.Basic
import MyMathlibProject.SeqHelper
import Mathlib.Data.Seq.Basic

/-!
# Weak transitions

A probabilistic forward simulation between two PLTS over a common label
alphabet is a state relation `R` such that initial concrete states are
matched by initial abstract states with which they are `R`-related, and every
concrete transition can be matched by an abstract transition whose resulting
distribution is related to the concrete one in the sense of a *coupling*: a
joint distribution with the appropriate marginals whose support lies in `R`.
-/

open Stream'

namespace PLTS

variable {α β State State_C State_A Label : Type}

/-! ### Internal/external labels and weak transitions -/

/-- A system together with a partition of its labels into internal (silent)
and external (observable) labels: `ls.internal l` says that `l` is internal,
and external labels are exactly the labels `l` with `¬ ls.internal l`. -/
structure LabelledSystem (State Label : Type) extends System State Label where
  internal : Label → Prop

/-! ### Traces -/

/-- The trace of a (possibly infinite) execution `e` under a labelled system
`ls`: the sequence of external labels appearing in `e.trans`, in order, with
internal (τ) labels dropped. Finite if `e` has finitely many external
transitions, infinite otherwise. -/
noncomputable def LabelledSystem.trace (ls : LabelledSystem State Label)
    (e : AlterSeq State Label) : Seq Label :=
  (e.trans.filter (fun p => ¬ ls.internal p.1)).map Prod.fst

/-- The trace of an execution with no transitions is the empty sequence. -/
@[simp] theorem LabelledSystem.trace_init
    (ls : LabelledSystem State Label) (s : State) :
    ls.trace ⟨s, (Seq.nil : Seq (Label × State))⟩ = (Seq.nil : Seq Label) := by
  simp [LabelledSystem.trace]

/-- The trace of an execution whose first transition has an *external* label
`l` starts with `l`, followed by the trace from the rest of the execution. -/
@[simp] theorem LabelledSystem.trace_cons_external
    (ls : LabelledSystem State Label) (s : State) (l : Label) (s' : State)
    (rest : Seq (Label × State)) (h : ¬ ls.internal l) :
    ls.trace ⟨s, Seq.cons (l, s') rest⟩ = Seq.cons l (ls.trace ⟨s', rest⟩) := by
  unfold LabelledSystem.trace
  rw [Seq.filter_cons_pos (l, s') rest h, Seq.map_cons]

/-- The trace of an execution whose first transition has an *internal* label
`l` equals the trace from the rest of the execution (the internal label is
dropped). -/
@[simp] theorem LabelledSystem.trace_cons_internal
    (ls : LabelledSystem State Label) (s : State) (l : Label) (s' : State)
    (rest : Seq (Label × State)) (h : ls.internal l) :
    ls.trace ⟨s, Seq.cons (l, s') rest⟩ = ls.trace ⟨s', rest⟩ := by
  unfold LabelledSystem.trace
  rw [Seq.filter_cons_neg (l, s') rest (fun h' => h' h)]

/-- A finite execution is *trace-tight* under `ls` if either it has no
transitions, or its last transition is external. Tight executions correspond
to "trace cone boundaries": each trajectory has at most one tight prefix per
finite trace.

This rules out the artefact where a single trajectory contributes to the
trace probability *infinitely many times* via nested cylinders — a finite
prefix and any of its extensions by trailing internal transitions all have
the same trace, but only one of them (the shortest, ending right after the
last external transition or with no transitions at all) is tight. -/
def LabelledSystem.IsTight
    (ls : LabelledSystem State Label) (e : AlterSeq State Label) : Prop :=
  e.trans.TerminatedAt 0 ∨
  ∃ (n : ℕ) (l : Label) (s : State),
    e.trans.get? n = some (l, s) ∧
    e.trans.TerminatedAt (n + 1) ∧
    ¬ ls.internal l

/-- The probability that the probabilistic execution `pe` produces the finite
trace `τ` under `ls`: the (countable) sum of `pe.probOf` over all
*trace-tight* finite executions `e` with `ls.trace e = τ`.

The tightness condition (`IsTight`) ensures the summands correspond to
disjoint cylinders in the trace cone for `τ`: a trajectory contributes
exactly once via its unique tight prefix (the shortest prefix with trace `τ`,
ending right after the last external transition). Without tightness, internal
loops would cause double-counting — see the docstring of `IsTight` for the
artefact this prevents.

For finite `τ` this is the standard trace-cone probability (i.e. the
probability that the trajectory's first `|τ|` external labels are exactly
`τ`). For infinite `τ` the sum is `0` since no finite execution has an
infinite trace; capturing infinite-trace probabilities would require moving
to a measure-theoretic setting on the σ-algebra generated by trace cones. -/
noncomputable def LabelledSystem.traceProb (ls : LabelledSystem State Label)
    (pe : ProbabilisticExecution ls.toSystem) (τ : Seq Label) : ENNReal :=
  ∑' e : {e : AlterSeq State Label //
      e.trans.Terminates ∧ ls.trace e = τ ∧ ls.IsTight e},
    pe.probOf e.1 e.2.1

/-! ### Trace-distribution sets achievable by a system -/

/-- The set of trace distributions achievable by some probabilistic execution
of the labelled system `ls` **that starts at the system's initial state**, i.e.
whose initial distribution is the Dirac `PMF.pure ls.init`. Equality of this set
across two systems means the systems are trace-distribution-equivalent.

The Dirac-init requirement is essential: it restricts to executions that
correspond to genuine runs of `ls` from its designated start state. Without it
the `𝒟(sys)` lift admits mixture initial distributions over `PMF State` that no
single `sys`-execution realises, and the trace-distribution equivalence fails
(the `𝒟`-side `belief` reconstruction is unsound for mixture inits). -/
def achievableTraceDists (ls : LabelledSystem State Label) :
    Set (Seq Label → ENNReal) :=
  {D | ∃ pe : ProbabilisticExecution ls.toSystem,
    pe.initState = PMF.pure ls.toSystem.init ∧ ∀ τ, ls.traceProb pe τ = D τ}

/-! ### Weak Schedulers -/

/-- A *weak scheduler* for a labelled system: a `Scheduler` whose emissions are
restricted to internal labels. The unbounded number of τ-steps to take when
running is supplied externally to `run` (rather than baked into the scheduler),
so this structure has no `runtime` field. -/
structure WeakScheduler (sys : LabelledSystem State Label)
    extends Scheduler sys.toSystem where
  internal_only : ∀ (e : AlterSeq State Label) (l : Label) (μ : PMF State),
    some (l, μ) ∈ (next e).support → sys.internal l

namespace WeakScheduler

variable {sys : LabelledSystem State Label}

/-- Run the weak scheduler from a prefix `e` with current state `s`, for `n`
iterations. After `n` recursions (or upon hitting a `none` output) the result
is the Dirac on the current state. -/
noncomputable def runFromState (σ : WeakScheduler sys) :
    ℕ → AlterSeq State Label → State → PMF State
  | 0,     _, s => PMF.pure s
  | n + 1, e, s => (σ.next e).bind fun
    | none           => PMF.pure s
    | some (l, μ_q) => μ_q.bind fun s' =>
        σ.runFromState n ⟨e.init, e.trans.append (Seq.cons (l, s') Seq.nil)⟩ s'

/-- Run the weak scheduler from a single state `s` for `n` iterations,
starting from the trivial prefix `⟨s, Seq.nil⟩`. The fuel `n` is now an
external parameter (previously a field on `WeakScheduler`). -/
noncomputable def run (σ : WeakScheduler sys) (n : ℕ) (s : State) : PMF State :=
  σ.runFromState n ⟨s, Seq.nil⟩ s

/-- The weak scheduler that immediately stops on every prefix. Used to witness
reflexivity of weak transitions: it takes no τ-steps, so its run from any state
`s` is the Dirac `PMF.pure s` regardless of the fuel. -/
noncomputable def stop (sys : LabelledSystem State Label) : WeakScheduler sys where
  next _ := PMF.pure none
  valid e _ _ _ _ l μ h := by simp at h
  internal_only e l μ h := by simp at h

/-- `(stop sys).runFromState n e s` is always the Dirac on `s`, since the
scheduler emits `none` immediately. -/
private theorem runFromState_stop (sys : LabelledSystem State Label) :
    ∀ (n : ℕ) (e : AlterSeq State Label) (s : State),
      (stop sys).runFromState n e s = PMF.pure s := by
  intro n
  induction n with
  | zero => intros; rfl
  | succ n ih =>
    intro e s
    change ((stop sys).next e).bind _ = PMF.pure s
    simp only [stop, PMF.pure_bind]

@[simp] theorem run_stop (sys : LabelledSystem State Label) (n : ℕ) (s : State) :
    (stop sys).run n s = PMF.pure s :=
  runFromState_stop sys n ⟨s, Seq.nil⟩ s

/-- The fuel-bounded variant of a WeakScheduler: behaves as `σ` until the
prefix's transition sequence has accumulated `n` or more entries, then forces
a halt by emitting `none`. The resulting scheduler halts after at most `n`
outer steps when run via `run n` (since each outer step extends the prefix by
exactly one transition; starting from the empty prefix, after `n` steps the
seq has `n` entries and `(σ.boundedFuel n).next` would emit `none`). -/
noncomputable def boundedFuel (σ : WeakScheduler sys) (n : ℕ) : WeakScheduler sys where
  next e :=
    open Classical in
    -- Active iff the prefix has fewer than `n` transitions, i.e.,
    -- `e.trans.TerminatedAt (n - 1)` (for `n ≥ 1`) — equivalently
    -- `∃ k, k < n ∧ e.trans.TerminatedAt k`.
    if (∃ k, k < n ∧ e.trans.TerminatedAt k) then σ.next e
    else PMF.pure none
  valid := by
    intro e k s h_term h_state l μ h_supp
    classical
    by_cases h_act : (∃ k, k < n ∧ e.trans.TerminatedAt k)
    · have h_eq : (if (∃ k, k < n ∧ e.trans.TerminatedAt k) then σ.next e
                    else PMF.pure none) = σ.next e := if_pos h_act
      rw [h_eq] at h_supp
      exact σ.valid e k s h_term h_state l μ h_supp
    · have h_eq : (if (∃ k, k < n ∧ e.trans.TerminatedAt k) then σ.next e
                    else PMF.pure none) = PMF.pure none := if_neg h_act
      rw [h_eq, PMF.mem_support_pure_iff] at h_supp
      exact absurd h_supp (by simp)
  internal_only := by
    intro e l μ h_supp
    classical
    by_cases h_act : (∃ k, k < n ∧ e.trans.TerminatedAt k)
    · have h_eq : (if (∃ k, k < n ∧ e.trans.TerminatedAt k) then σ.next e
                    else PMF.pure none) = σ.next e := if_pos h_act
      rw [h_eq] at h_supp
      exact σ.internal_only e l μ h_supp
    · have h_eq : (if (∃ k, k < n ∧ e.trans.TerminatedAt k) then σ.next e
                    else PMF.pure none) = PMF.pure none := if_neg h_act
      rw [h_eq, PMF.mem_support_pure_iff] at h_supp
      exact absurd h_supp (by simp)

/-- `(σ.boundedFuel n).next e` reduces to `σ.next e` whenever the prefix's
transition sequence has accumulated fewer than `n` entries. -/
theorem boundedFuel_next_of_active (σ : WeakScheduler sys) (n : ℕ)
    (e : AlterSeq State Label) (h : ∃ k, k < n ∧ e.trans.TerminatedAt k) :
    (σ.boundedFuel n).next e = σ.next e := by
  classical
  change (if (∃ k, k < n ∧ e.trans.TerminatedAt k) then σ.next e
            else PMF.pure none) = _
  exact if_pos h

/-- Auxiliary lemma: `boundedFuel n`'s `runFromState k` matches `σ.runFromState k`
whenever the current prefix `e` has accumulated at most `n - k` transitions
(so even if we add `k` more transitions, the prefix length stays ≤ n, leaving
the bounded scheduler in its "active" branch). Concretely we require
`e.trans.TerminatedAt (n - k)` (for `k ≥ 1` this is enough to derive active
on the current prefix; for `k = 0` the conclusion is trivial). -/
private theorem runFromState_boundedFuel_eq_aux (σ : WeakScheduler sys) (n : ℕ) :
    ∀ (k : ℕ) (e : AlterSeq State Label) (s : State),
      k ≤ n →
      e.trans.TerminatedAt (n - k) →
      (σ.boundedFuel n).runFromState k e s = σ.runFromState k e s := by
  intro k
  induction k with
  | zero =>
    intro e s _h_le _h_term
    -- Both sides equal `PMF.pure s`.
    rfl
  | succ m ih =>
    intro e s h_le h_term
    have h_le' : m ≤ n := Nat.le_of_succ_le h_le
    -- We have `e.trans.TerminatedAt (n - (m+1))`. From `m + 1 ≤ n` we get
    -- `n - (m+1) < n`, so the active-witness `(n - (m+1))` validates
    -- `boundedFuel.next e = σ.next e`. After one step, the prefix grows by 1
    -- and the new prefix is `TerminatedAt (n - m)` by `terminatedAt_append`.
    have h_active : ∃ k, k < n ∧ e.trans.TerminatedAt k :=
      ⟨n - (m + 1), by omega, h_term⟩
    have h_next : (σ.boundedFuel n).next e = σ.next e :=
      boundedFuel_next_of_active σ n e h_active
    -- Unfold one step of `runFromState` and rewrite the head emission PMF.
    change ((σ.boundedFuel n).next e).bind (fun
        | none => PMF.pure s
        | some (l, μ_q) => μ_q.bind fun s' =>
            (σ.boundedFuel n).runFromState m
              ⟨e.init, e.trans.append (Seq.cons (l, s') Seq.nil)⟩ s')
      = (σ.next e).bind (fun
        | none => PMF.pure s
        | some (l, μ_q) => μ_q.bind fun s' =>
            σ.runFromState m
              ⟨e.init, e.trans.append (Seq.cons (l, s') Seq.nil)⟩ s')
    rw [h_next]
    -- Body congruence; both binds are over `σ.next e`.
    congr 1
    funext sub
    rcases sub with _ | ⟨l, μ_q⟩
    · -- `none` branch: both sides are `PMF.pure s`.
      rfl
    · -- `some (l, μ_q)` branch: bind μ_q with the inductive equality.
      change μ_q.bind (fun s' => (σ.boundedFuel n).runFromState m
          ⟨e.init, e.trans.append (Seq.cons (l, s') Seq.nil)⟩ s')
        = μ_q.bind (fun s' => σ.runFromState m
            ⟨e.init, e.trans.append (Seq.cons (l, s') Seq.nil)⟩ s')
      congr 1
      funext s'
      -- Apply IH; need to show the extended prefix is `TerminatedAt (n - m)`.
      refine ih _ _ h_le' ?_
      -- The extended prefix's seq is `e.trans.append (cons (l, s') nil)`,
      -- which is `TerminatedAt (Nat.find ⟨n - (m+1), h_term⟩ + 1)`, hence
      -- by `terminated_stable` upward at `n - m`.
      have h_app_term : (e.trans.append (Seq.cons (l, s') Seq.nil)).TerminatedAt
          (Nat.find (⟨n - (m + 1), h_term⟩ : e.trans.Terminates) + 1) :=
        Stream'.Seq.terminatedAt_append_find ⟨n - (m + 1), h_term⟩
          (show (Seq.cons (l, s') Seq.nil : Seq (Label × State)).TerminatedAt 1
            from rfl)
      have h_find_le : Nat.find (⟨n - (m + 1), h_term⟩ : e.trans.Terminates) ≤
          n - (m + 1) := Nat.find_le h_term
      change (e.trans.append (Seq.cons (l, s') Seq.nil)).TerminatedAt (n - m)
      apply Stream'.Seq.terminated_stable _ _ h_app_term
      omega

/-- Running `σ.boundedFuel n` for `n` steps from `⟨s, Seq.nil⟩` yields the same
PMF as running `σ` for `n` steps. -/
theorem run_boundedFuel_eq (σ : WeakScheduler sys) (n : ℕ) (s : State) :
    (σ.boundedFuel n).run n s = σ.run n s := by
  unfold run
  refine runFromState_boundedFuel_eq_aux σ n n ⟨s, Seq.nil⟩ s (le_refl _) ?_
  -- `(Seq.nil).TerminatedAt (n - n) = TerminatedAt 0`, which holds.
  rw [Nat.sub_self]
  change (Seq.nil : Seq (Label × State)).TerminatedAt 0
  rfl

/-- For any weak scheduler `σ`, state `s`, and fuel `n`, the mass that
`σ.run n s` places on `s` is at least the probability that `σ`'s first emission
from `⟨s, Seq.nil⟩` is `none` (i.e., immediately halts, keeping the chain at
`s`). For `n = 0` the inequality is `σ.next none ≤ 1`; for `n = m+1`, the
`none`-branch in the bind contributes exactly `σ.next none × 1` to the mass at
`s`. -/
lemma run_apply_self_ge_next_none {sys : LabelledSystem State Label}
    (σ : WeakScheduler sys) (s : State) :
    ∀ n, σ.next ⟨s, Seq.nil⟩ none ≤ (σ.run n s) s := by
  intro n
  change σ.next ⟨s, Seq.nil⟩ none ≤ (σ.runFromState n ⟨s, Seq.nil⟩ s) s
  induction n with
  | zero =>
    -- runFromState 0 _ s = PMF.pure s.
    change σ.next ⟨s, Seq.nil⟩ none ≤ (PMF.pure s : PMF State) s
    rw [PMF.pure_apply, if_pos rfl]
    exact PMF.coe_le_one _ _
  | succ m _ =>
    -- runFromState (m+1) ⟨s, nil⟩ s = (σ.next ⟨s, nil⟩).bind (match-body).
    change σ.next ⟨s, Seq.nil⟩ none ≤
      ((σ.next ⟨s, Seq.nil⟩).bind (fun (sub_emit : Option (Label × PMF State)) =>
        match sub_emit with
        | none => (PMF.pure s : PMF State)
        | some (l, μ_q) => μ_q.bind fun s' =>
            σ.runFromState m ⟨s, Seq.nil.append (Seq.cons (l, s') Seq.nil)⟩ s')) s
    rw [PMF.bind_apply]
    -- Goal: σ.next none ≤ ∑' a, σ.next a * (match a with ...) s.
    refine le_trans ?_ (ENNReal.le_tsum (α := Option (Label × PMF State)) none)
    -- After ENNReal.le_tsum none: bound by σ.next none * (match none with ...) s
    --   = σ.next none * (PMF.pure s) s = σ.next none * 1 = σ.next none.
    change σ.next ⟨s, Seq.nil⟩ none ≤
      σ.next ⟨s, Seq.nil⟩ none * ((PMF.pure s : PMF State) s)
    rw [PMF.pure_apply, if_pos rfl, mul_one]

end WeakScheduler

/-- Weak (internal) transition `μ_init ⇒^τ μ` on initial distributions: there
exists a weak scheduler and a fuel `n` whose run, sampled over starting states
from `μ_init`, produces the distribution `μ`. The "from a single state" case is
recovered as `weakTau sys (PMF.pure s) μ`. -/
def weakTau (sys : LabelledSystem State Label)
    (μ_init : PMF State) (μ : PMF State) : Prop :=
  ∃ (σ : WeakScheduler sys) (n : ℕ), μ_init.bind (σ.run n) = μ

namespace weakTau

variable {sys : LabelledSystem State Label} {μ_init μ : PMF State}

/-- Classical extraction of the fuel from a `weakTau` proof. -/
noncomputable def witness_fuel (h : weakTau sys μ_init μ) : ℕ :=
  h.choose_spec.choose

/-- Classical extraction of the underlying `WeakScheduler` from a `weakTau`
proof, wrapped via `boundedFuel` to guarantee almost-sure termination within
`witness_fuel` outer steps. The wrapping preserves `run witness_fuel` (by
`run_boundedFuel_eq`), so `witness_run` still holds. -/
noncomputable def witness (h : weakTau sys μ_init μ) : WeakScheduler sys :=
  h.choose.boundedFuel h.witness_fuel

/-- The extracted scheduler, when run from `μ_init` for the extracted fuel,
reaches `μ`. -/
theorem witness_run (h : weakTau sys μ_init μ) :
    μ_init.bind (h.witness.run h.witness_fuel) = μ := by
  unfold witness
  -- Replace the boundedFuel run with the original run pointwise via funext.
  have h_run_eq : ∀ s : State,
      (h.choose.boundedFuel h.witness_fuel).run h.witness_fuel s
        = h.choose.run h.witness_fuel s := fun s =>
    WeakScheduler.run_boundedFuel_eq h.choose h.witness_fuel s
  rw [show (h.choose.boundedFuel h.witness_fuel).run h.witness_fuel
        = h.choose.run h.witness_fuel from funext h_run_eq]
  exact h.choose_spec.choose_spec

end weakTau

/-- Reflexivity of `weakTau`: every distribution is weak-τ-related to itself,
witnessed by the stop-everywhere weak scheduler. -/
theorem weakTau_refl (ls : LabelledSystem State Label) (μ : PMF State) :
    weakTau ls μ μ := by
  refine ⟨WeakScheduler.stop ls, 0, ?_⟩
  show μ.bind _ = μ
  have heq : (WeakScheduler.stop ls).run 0 = PMF.pure := funext fun _ => rfl
  rw [heq]
  exact PMF.bind_pure μ

/-- The lifting of `sys.step` from `State → Label → PMF State → Prop` to a
relation on initial and final distributions, parameterised by a label, *closed
under convex combinations* of valid system steps.

`hyperStep sys μ_pre l μ_post` holds iff there is an assignment
`p : State → PMF (PMF State)` choosing, for every starting state, a
randomised mixture of successor-distributions, such that

* every `s ∈ μ_pre.support` and every `μ ∈ (p s).support` takes a valid step
  `sys.step s l μ`;
* `μ_post` is the resulting bind:
  `μ_post = μ_pre.bind (fun s => (p s).bind id)`.

Allowing `p s` to be a `PMF (PMF State)` (rather than a single `PMF State`)
makes the relation closed under convex combinations of hyper-steps. In the
singleton case `μ_pre = PMF.pure s` it reduces to: `μ_post` is in the convex
hull of `{μ | sys.step s l μ}`. Every state in `μ_pre.support` must
contribute a real step — there is no stutter freedom for internal labels. -/
def hyperStep (sys : LabelledSystem State Label)
    (μ_pre : PMF State) (l : Label) (μ_post : PMF State) : Prop :=
  ∃ p : State → PMF (PMF State),
    (∀ s ∈ μ_pre.support, ∀ μ ∈ (p s).support, sys.step s l μ) ∧
    μ_post = μ_pre.bind (fun s => (p s).bind id)

namespace hyperStep

variable {sys : LabelledSystem State Label} {μ_pre μ_post : PMF State} {l : Label}

/-- Classical extraction of the per-state successor kernel from a `hyperStep`
proof. -/
noncomputable def kernel (h : hyperStep sys μ_pre l μ_post) :
    State → PMF (PMF State) := h.choose

/-- Every distribution in the kernel's support is a valid system step. -/
theorem kernel_step (h : hyperStep sys μ_pre l μ_post) :
    ∀ s ∈ μ_pre.support, ∀ μ ∈ (h.kernel s).support, sys.step s l μ :=
  h.choose_spec.1

/-- The post-distribution is the bind of `μ_pre` with the flattened kernel. -/
theorem post_eq_bind (h : hyperStep sys μ_pre l μ_post) :
    μ_post = μ_pre.bind (fun s => (h.kernel s).bind id) :=
  h.choose_spec.2

end hyperStep

/-- A strong system step lifts to a hyper-step on a singleton initial
distribution: if `sys.step s l μ`, then `hyperStep sys (PMF.pure s) l μ`. -/
theorem hyperStep_pure_of_step
    {sys : LabelledSystem State Label} {s : State} {l : Label} {μ : PMF State}
    (h : sys.step s l μ) :
    hyperStep sys (PMF.pure s) l μ := by
  refine ⟨fun _ => PMF.pure μ, ?_, ?_⟩
  · intro s' h_s' μ' h_μ'
    rw [PMF.mem_support_pure_iff] at h_s' h_μ'
    subst h_s'
    subst h_μ'
    exact h
  · simp [PMF.pure_bind]

/-- The weak external step `μ_init ⇒^l μ_final`, composing the three layers
`τ-closure → hyper-step with label l → τ-closure`. Concretely there exist
intermediate distributions `μ, μ'` with

* `μ_init ⇒^τ μ` (a `weakTau`),
* `μ -[l]→ μ'` (a `hyperStep` with label `l`),
* `μ' ⇒^τ μ_final` (another `weakTau`).

Defined uniformly for any label `l`. For external (non-`internal`) labels this
is the standard weak step; for internal labels it is one strictly forced
internal hyper-step sandwiched between two τ-closures (which is *not* the same
as `weakTau` — for τ-labels, prefer `weakTau` directly). -/
def weakStep (sys : LabelledSystem State Label)
    (μ_init : PMF State) (l : Label) (μ_final : PMF State) : Prop :=
  ∃ μ μ' : PMF State,
    weakTau sys μ_init μ ∧
    hyperStep sys μ l μ' ∧
    weakTau sys μ' μ_final

namespace weakStep

variable {sys : LabelledSystem State Label} {μ_init μ_final : PMF State} {l : Label}

/-- Classical extraction of the post-τ-closure intermediate distribution. -/
noncomputable def preDist (h : weakStep sys μ_init l μ_final) : PMF State :=
  h.choose

/-- Classical extraction of the post-`l`-step intermediate distribution. -/
noncomputable def postDist (h : weakStep sys μ_init l μ_final) : PMF State :=
  h.choose_spec.choose

/-- The τ-closure before the external step. -/
theorem weakTau_pre (h : weakStep sys μ_init l μ_final) :
    weakTau sys μ_init h.preDist :=
  h.choose_spec.choose_spec.1

/-- The external step itself, as a `hyperStep`. -/
theorem hyperStep_mid (h : weakStep sys μ_init l μ_final) :
    hyperStep sys h.preDist l h.postDist :=
  h.choose_spec.choose_spec.2.1

/-- The τ-closure after the external step. -/
theorem weakTau_post (h : weakStep sys μ_init l μ_final) :
    weakTau sys h.postDist μ_final :=
  h.choose_spec.choose_spec.2.2

end weakStep

/-- A strong system step lifts to a weak step on a singleton initial
distribution: if `sys.step s l μ`, then `weakStep sys (PMF.pure s) l μ`. Both
τ-closure layers are trivial reflexivities. -/
theorem weakStep_strong {ls : LabelledSystem State Label}
    {s : State} {l : Label} {μ : PMF State}
    (h_step : ls.step s l μ) :
    weakStep ls (PMF.pure s) l μ :=
  ⟨PMF.pure s, μ, weakTau_refl ls (PMF.pure s),
    hyperStep_pure_of_step h_step, weakTau_refl ls μ⟩

/-- A strong system step at an *internal* label lifts to a `weakTau` from the
Dirac source: a one-step WeakScheduler emitting `(l, μ)` witnesses
`weakTau ls (PMF.pure s) μ`. -/
theorem weakTau_of_step {ls : LabelledSystem State Label}
    {s : State} {l : Label} {μ : PMF State}
    (h_int : ls.internal l) (h_step : ls.step s l μ) :
    weakTau ls (PMF.pure s) μ := by
  classical
  -- The single-step WeakScheduler: emit `(l, μ)` deterministically on the
  -- initial prefix `⟨s, Seq.nil⟩`; halt everywhere else.
  let σ : WeakScheduler ls :=
    { next := fun e' =>
        if e'.init = s ∧ e'.trans = Seq.nil then PMF.pure (some (l, μ))
        else PMF.pure none
      valid := by
        intro e' n s' h_term h_state l' μ' h_supp
        by_cases h_cond : e'.init = s ∧ e'.trans = Seq.nil
        · simp only [if_pos h_cond, PMF.mem_support_pure_iff,
            Option.some.injEq, Prod.mk.injEq] at h_supp
          obtain ⟨h_l, h_μ⟩ := h_supp
          subst h_l; subst h_μ
          have h_init_eq : s' = s := by
            rcases Nat.eq_zero_or_pos n with hn | hn
            · subst hn
              have : e'.stateAt 0 = some e'.init := rfl
              rw [this, h_cond.1] at h_state
              exact (Option.some.inj h_state).symm
            · exfalso
              obtain ⟨k, hk⟩ := Nat.exists_eq_succ_of_ne_zero hn.ne'
              rw [hk] at h_state
              change (e'.trans.get? k).map Prod.snd = some s' at h_state
              rw [h_cond.2] at h_state
              simp at h_state
          rw [h_init_eq]; exact h_step
        · simp only [if_neg h_cond, PMF.mem_support_pure_iff] at h_supp
          exact absurd h_supp (by simp)
      internal_only := by
        intro e' l' μ' h_supp
        by_cases h_cond : e'.init = s ∧ e'.trans = Seq.nil
        · simp only [if_pos h_cond, PMF.mem_support_pure_iff,
            Option.some.injEq, Prod.mk.injEq] at h_supp
          rw [h_supp.1]; exact h_int
        · simp only [if_neg h_cond, PMF.mem_support_pure_iff] at h_supp
          exact absurd h_supp (by simp) }
  refine ⟨σ, 1, ?_⟩
  -- (PMF.pure s).bind (σ.run 1) = σ.run 1 s = σ.runFromState 1 ⟨s, nil⟩ s.
  rw [PMF.pure_bind]
  -- Unfold σ.run, σ.runFromState 1, σ.next ⟨s, nil⟩ = PMF.pure (some (l, μ)).
  change σ.runFromState 1 ⟨s, Seq.nil⟩ s = μ
  have h_next : σ.next ⟨s, Seq.nil⟩ = PMF.pure (some (l, μ)) := by
    change (if (⟨s, Seq.nil⟩ : AlterSeq State Label).init = s ∧
        (⟨s, Seq.nil⟩ : AlterSeq State Label).trans = Seq.nil
        then PMF.pure (some (l, μ)) else PMF.pure none) = PMF.pure (some (l, μ))
    rw [if_pos ⟨rfl, rfl⟩]
  change (σ.next ⟨s, Seq.nil⟩).bind _ = μ
  rw [h_next, PMF.pure_bind]
  -- The "some (l, μ)" branch: μ.bind (fun s' => σ.runFromState 0 ... s') = μ.bind PMF.pure = μ.
  -- `runFromState 0 _ s' = PMF.pure s'` by definition.
  change μ.bind (fun s' => PMF.pure s') = μ
  exact PMF.bind_pure μ

end PLTS
