/-
Copyright (c) 2026 Gaspard Reghem. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Gaspard Reghem
-/

import MyMathlibProject.Basic
import MyMathlibProject.SeqHelper
import Mathlib.Data.Seq.Basic

/-!
# Weak transitions

A probabilistic forward simulation between two PLTS over a common label
alphabet is a state relation `R` such that initial concrete states are
matched by initial abstract states with which they are `R`-related, and every
concrete transition can be matched by an abstract transition whose resulting
distribution is related to the concrete one in the sense of a *coupling*: a
joint distribution with the appropriate marginals whose support lies in `R`.
-/

open Stream'

namespace PLTS

variable {α β State State_C State_A Label : Type}

/-! ### Internal/external labels and weak transitions -/

/-- A system together with a partition of its labels into internal (silent)
and external (observable) labels: `ls.internal l` says that `l` is internal,
and external labels are exactly the labels `l` with `¬ ls.internal l`. -/
structure LabelledSystem (State Label : Type) extends System State Label where
  internal : Label → Prop

/-! ### Traces -/

/-- The trace of a (possibly infinite) execution `e` under a labelled system
`ls`: the sequence of external labels appearing in `e.trans`, in order, with
internal (τ) labels dropped. Finite if `e` has finitely many external
transitions, infinite otherwise. -/
noncomputable def LabelledSystem.trace (ls : LabelledSystem State Label)
    (e : AlterSeq State Label) : Seq Label :=
  (e.trans.filter (fun p => ¬ ls.internal p.1)).map Prod.fst

/-- The trace of an execution with no transitions is the empty sequence. -/
@[simp] theorem LabelledSystem.trace_init
    (ls : LabelledSystem State Label) (s : State) :
    ls.trace ⟨s, (Seq.nil : Seq (Label × State))⟩ = (Seq.nil : Seq Label) := by
  simp [LabelledSystem.trace]

/-- The trace of an execution whose first transition has an *external* label
`l` starts with `l`, followed by the trace from the rest of the execution. -/
@[simp] theorem LabelledSystem.trace_cons_external
    (ls : LabelledSystem State Label) (s : State) (l : Label) (s' : State)
    (rest : Seq (Label × State)) (h : ¬ ls.internal l) :
    ls.trace ⟨s, Seq.cons (l, s') rest⟩ = Seq.cons l (ls.trace ⟨s', rest⟩) := by
  unfold LabelledSystem.trace
  rw [Seq.filter_cons_pos (l, s') rest h, Seq.map_cons]

/-- The trace of an execution whose first transition has an *internal* label
`l` equals the trace from the rest of the execution (the internal label is
dropped). -/
@[simp] theorem LabelledSystem.trace_cons_internal
    (ls : LabelledSystem State Label) (s : State) (l : Label) (s' : State)
    (rest : Seq (Label × State)) (h : ls.internal l) :
    ls.trace ⟨s, Seq.cons (l, s') rest⟩ = ls.trace ⟨s', rest⟩ := by
  unfold LabelledSystem.trace
  rw [Seq.filter_cons_neg (l, s') rest (fun h' => h' h)]

/-- A finite execution is *trace-tight* under `ls` if either it has no
transitions, or its last transition is external. Tight executions correspond
to "trace cone boundaries": each trajectory has at most one tight prefix per
finite trace.

This rules out the artefact where a single trajectory contributes to the
trace probability *infinitely many times* via nested cylinders — a finite
prefix and any of its extensions by trailing internal transitions all have
the same trace, but only one of them (the shortest, ending right after the
last external transition or with no transitions at all) is tight. -/
def LabelledSystem.IsTight
    (ls : LabelledSystem State Label) (e : AlterSeq State Label) : Prop :=
  e.trans.TerminatedAt 0 ∨
  ∃ (n : ℕ) (l : Label) (s : State),
    e.trans.get? n = some (l, s) ∧
    e.trans.TerminatedAt (n + 1) ∧
    ¬ ls.internal l

/-- The probability that the probabilistic execution `pe` produces the finite
trace `τ` under `ls`: the (countable) sum of `pe.probOf` over all
*trace-tight* finite executions `e` with `ls.trace e = τ`.

The tightness condition (`IsTight`) ensures the summands correspond to
disjoint cylinders in the trace cone for `τ`: a trajectory contributes
exactly once via its unique tight prefix (the shortest prefix with trace `τ`,
ending right after the last external transition). Without tightness, internal
loops would cause double-counting — see the docstring of `IsTight` for the
artefact this prevents.

For finite `τ` this is the standard trace-cone probability (i.e. the
probability that the trajectory's first `|τ|` external labels are exactly
`τ`). For infinite `τ` the sum is `0` since no finite execution has an
infinite trace; capturing infinite-trace probabilities would require moving
to a measure-theoretic setting on the σ-algebra generated by trace cones. -/
noncomputable def LabelledSystem.traceProb (ls : LabelledSystem State Label)
    (pe : ProbabilisticExecution ls.toSystem) (τ : Seq Label) : ENNReal :=
  ∑' e : {e : AlterSeq State Label //
      e.trans.Terminates ∧ ls.trace e = τ ∧ ls.IsTight e},
    pe.probOf e.1 e.2.1

/-! ### Weak Schedulers -/

/-- A *weak scheduler* for a labelled system: a `Scheduler` whose emissions are
restricted to internal labels. The unbounded number of τ-steps to take when
running is supplied externally to `run` (rather than baked into the scheduler),
so this structure has no `runtime` field. -/
structure WeakScheduler (sys : LabelledSystem State Label)
    extends Scheduler sys.toSystem where
  internal_only : ∀ (e : AlterSeq State Label) (l : Label) (μ : PMF State),
    some (l, μ) ∈ (next e).support → sys.internal l

namespace WeakScheduler

variable {sys : LabelledSystem State Label}

/-- Run the weak scheduler from a prefix `e` with current state `s`, for `n`
iterations. After `n` recursions (or upon hitting a `none` output) the result
is the Dirac on the current state. -/
noncomputable def runFromState (σ : WeakScheduler sys) :
    ℕ → AlterSeq State Label → State → PMF State
  | 0,     _, s => PMF.pure s
  | n + 1, e, s => (σ.next e).bind fun
    | none           => PMF.pure s
    | some (l, μ_q) => μ_q.bind fun s' =>
        σ.runFromState n ⟨e.init, e.trans.append (Seq.cons (l, s') Seq.nil)⟩ s'

/-- Run the weak scheduler from a single state `s` for `n` iterations,
starting from the trivial prefix `⟨s, Seq.nil⟩`. The fuel `n` is now an
external parameter (previously a field on `WeakScheduler`). -/
noncomputable def run (σ : WeakScheduler sys) (n : ℕ) (s : State) : PMF State :=
  σ.runFromState n ⟨s, Seq.nil⟩ s

/-- The weak scheduler that immediately stops on every prefix. Used to witness
reflexivity of weak transitions: it takes no τ-steps, so its run from any state
`s` is the Dirac `PMF.pure s` regardless of the fuel. -/
noncomputable def stop (sys : LabelledSystem State Label) : WeakScheduler sys where
  next _ := PMF.pure none
  valid e _ _ _ _ l μ h := by simp at h
  internal_only e l μ h := by simp at h

/-- `(stop sys).runFromState n e s` is always the Dirac on `s`, since the
scheduler emits `none` immediately. -/
private theorem runFromState_stop (sys : LabelledSystem State Label) :
    ∀ (n : ℕ) (e : AlterSeq State Label) (s : State),
      (stop sys).runFromState n e s = PMF.pure s := by
  intro n
  induction n with
  | zero => intros; rfl
  | succ n ih =>
    intro e s
    change ((stop sys).next e).bind _ = PMF.pure s
    simp only [stop, PMF.pure_bind]

@[simp] theorem run_stop (sys : LabelledSystem State Label) (n : ℕ) (s : State) :
    (stop sys).run n s = PMF.pure s :=
  runFromState_stop sys n ⟨s, Seq.nil⟩ s

end WeakScheduler

/-- Weak (internal) transition `μ_init ⇒^τ μ` on initial distributions: there
exists a weak scheduler and a fuel `n` whose run, sampled over starting states
from `μ_init`, produces the distribution `μ`. The "from a single state" case is
recovered as `weakTau sys (PMF.pure s) μ`. -/
def weakTau (sys : LabelledSystem State Label)
    (μ_init : PMF State) (μ : PMF State) : Prop :=
  ∃ (σ : WeakScheduler sys) (n : ℕ), μ_init.bind (σ.run n) = μ

namespace weakTau

variable {sys : LabelledSystem State Label} {μ_init μ : PMF State}

/-- Classical extraction of the underlying `WeakScheduler` from a `weakTau`
proof. -/
noncomputable def witness (h : weakTau sys μ_init μ) : WeakScheduler sys :=
  h.choose

/-- Classical extraction of the fuel from a `weakTau` proof. -/
noncomputable def witness_fuel (h : weakTau sys μ_init μ) : ℕ :=
  h.choose_spec.choose

/-- The extracted scheduler, when run from `μ_init` for the extracted fuel,
reaches `μ`. -/
theorem witness_run (h : weakTau sys μ_init μ) :
    μ_init.bind (h.witness.run h.witness_fuel) = μ :=
  h.choose_spec.choose_spec

end weakTau

/-- Reflexivity of `weakTau`: every distribution is weak-τ-related to itself,
witnessed by the stop-everywhere weak scheduler. -/
theorem weakTau_refl (ls : LabelledSystem State Label) (μ : PMF State) :
    weakTau ls μ μ := by
  refine ⟨WeakScheduler.stop ls, 0, ?_⟩
  show μ.bind _ = μ
  have heq : (WeakScheduler.stop ls).run 0 = PMF.pure := funext fun _ => rfl
  rw [heq]
  exact PMF.bind_pure μ

/-- The lifting of `sys.step` from `State → Label → PMF State → Prop` to a
relation on initial and final distributions, parameterised by a label, *closed
under convex combinations* of valid system steps — and, when `l` is *internal*,
allowing some (but not all) starting states to *stutter* (contribute the Dirac
`PMF.pure s` instead of taking a real step).

`hyperStep sys μ_pre l μ_post` holds iff there is an assignment
`p : State → PMF (PMF State)` choosing, for every starting state, a
randomised mixture of successor-distributions or stutters, such that

* every `s ∈ μ_pre.support` and every `μ ∈ (p s).support` either takes a valid
  step `sys.step s l μ` or stutters (`μ = PMF.pure s`, allowed only when
  `sys.internal l`);
* when `l` is internal, at least one starting state must take a *real* step
  (the "not all stutter" condition); for external labels the disjunct above
  forces a real step at every output anyway, so the condition is automatic;
* `μ_post` is the resulting bind:
  `μ_post = μ_pre.bind (fun s => (p s).bind id)`.

Allowing `p s` to be a `PMF (PMF State)` (rather than a single `PMF State`)
makes the relation closed under convex combinations of hyper-steps. In the
singleton case `μ_pre = PMF.pure s` it reduces to: `μ_post` is in the convex
hull of `{μ | sys.step s l μ}` (the stutter clause is unreachable since the
sole state must take a real step). -/
def hyperStep (sys : LabelledSystem State Label)
    (μ_pre : PMF State) (l : Label) (μ_post : PMF State) : Prop :=
  ∃ p : State → PMF (PMF State),
    (∀ s ∈ μ_pre.support, ∀ μ ∈ (p s).support,
        sys.step s l μ ∨ (sys.internal l ∧ μ = PMF.pure s)) ∧
    (sys.internal l →
        ∃ s ∈ μ_pre.support, ∃ μ ∈ (p s).support, sys.step s l μ) ∧
    μ_post = μ_pre.bind (fun s => (p s).bind id)

namespace hyperStep

variable {sys : LabelledSystem State Label} {μ_pre μ_post : PMF State} {l : Label}

/-- Classical extraction of the per-state successor kernel from a `hyperStep`
proof. -/
noncomputable def kernel (h : hyperStep sys μ_pre l μ_post) :
    State → PMF (PMF State) := h.choose

/-- Every distribution in the kernel's support is either a valid system step
or a stutter at an internal label. -/
theorem kernel_step (h : hyperStep sys μ_pre l μ_post) :
    ∀ s ∈ μ_pre.support, ∀ μ ∈ (h.kernel s).support,
      sys.step s l μ ∨ (sys.internal l ∧ μ = PMF.pure s) :=
  h.choose_spec.1

/-- For internal labels, at least one starting state must take a real step
(the "not all stutter" guarantee). -/
theorem exists_step_of_internal (h : hyperStep sys μ_pre l μ_post)
    (h_int : sys.internal l) :
    ∃ s ∈ μ_pre.support, ∃ μ ∈ (h.kernel s).support, sys.step s l μ :=
  h.choose_spec.2.1 h_int

/-- The post-distribution is the bind of `μ_pre` with the flattened kernel. -/
theorem post_eq_bind (h : hyperStep sys μ_pre l μ_post) :
    μ_post = μ_pre.bind (fun s => (h.kernel s).bind id) :=
  h.choose_spec.2.2

end hyperStep

/-- A strong system step lifts to a hyper-step on a singleton initial
distribution: if `sys.step s l μ`, then `hyperStep sys (PMF.pure s) l μ`. -/
theorem hyperStep_pure_of_step
    {sys : LabelledSystem State Label} {s : State} {l : Label} {μ : PMF State}
    (h : sys.step s l μ) :
    hyperStep sys (PMF.pure s) l μ := by
  refine ⟨fun _ => PMF.pure μ, ?_, ?_, ?_⟩
  · -- Every output is a real step.
    intro s' h_s' μ' h_μ'
    rw [PMF.mem_support_pure_iff] at h_s' h_μ'
    subst h_s'
    subst h_μ'
    exact Or.inl h
  · -- For internal labels, the sole state in support takes a real step.
    intro _h_int
    refine ⟨s, ?_, μ, ?_, h⟩
    · rw [PMF.mem_support_pure_iff]
    · rw [PMF.mem_support_pure_iff]
  · simp [PMF.pure_bind]

/-- The weak external step `μ_init ⇒^l μ_final`, composing the three layers
`τ-closure → hyper-step with label l → τ-closure`. Concretely there exist
intermediate distributions `μ, μ'` with

* `μ_init ⇒^τ μ` (a `weakTau`),
* `μ -[l]→ μ'` (a `hyperStep` with label `l`),
* `μ' ⇒^τ μ_final` (another `weakTau`).

Defined uniformly for any label `l`. For external (non-`internal`) labels this
is the standard weak step; for internal labels it is one strictly forced
internal hyper-step sandwiched between two τ-closures (which is *not* the same
as `weakTau` — for τ-labels, prefer `weakTau` directly). -/
def weakStep (sys : LabelledSystem State Label)
    (μ_init : PMF State) (l : Label) (μ_final : PMF State) : Prop :=
  ∃ μ μ' : PMF State,
    weakTau sys μ_init μ ∧
    hyperStep sys μ l μ' ∧
    weakTau sys μ' μ_final

namespace weakStep

variable {sys : LabelledSystem State Label} {μ_init μ_final : PMF State} {l : Label}

/-- Classical extraction of the post-τ-closure intermediate distribution. -/
noncomputable def preDist (h : weakStep sys μ_init l μ_final) : PMF State :=
  h.choose

/-- Classical extraction of the post-`l`-step intermediate distribution. -/
noncomputable def postDist (h : weakStep sys μ_init l μ_final) : PMF State :=
  h.choose_spec.choose

/-- The τ-closure before the external step. -/
theorem weakTau_pre (h : weakStep sys μ_init l μ_final) :
    weakTau sys μ_init h.preDist :=
  h.choose_spec.choose_spec.1

/-- The external step itself, as a `hyperStep`. -/
theorem hyperStep_mid (h : weakStep sys μ_init l μ_final) :
    hyperStep sys h.preDist l h.postDist :=
  h.choose_spec.choose_spec.2.1

/-- The τ-closure after the external step. -/
theorem weakTau_post (h : weakStep sys μ_init l μ_final) :
    weakTau sys h.postDist μ_final :=
  h.choose_spec.choose_spec.2.2

end weakStep

/-- A strong system step lifts to a weak step on a singleton initial
distribution: if `sys.step s l μ`, then `weakStep sys (PMF.pure s) l μ`. Both
τ-closure layers are trivial reflexivities. -/
theorem weakStep_strong {ls : LabelledSystem State Label}
    {s : State} {l : Label} {μ : PMF State}
    (h_step : ls.step s l μ) :
    weakStep ls (PMF.pure s) l μ :=
  ⟨PMF.pure s, μ, weakTau_refl ls (PMF.pure s),
    hyperStep_pure_of_step h_step, weakTau_refl ls μ⟩

/-- A strong system step at an *internal* label lifts to a `weakTau` from the
Dirac source: a one-step WeakScheduler emitting `(l, μ)` witnesses
`weakTau ls (PMF.pure s) μ`. -/
theorem weakTau_of_step {ls : LabelledSystem State Label}
    {s : State} {l : Label} {μ : PMF State}
    (h_int : ls.internal l) (h_step : ls.step s l μ) :
    weakTau ls (PMF.pure s) μ := by
  classical
  -- The single-step WeakScheduler: emit `(l, μ)` deterministically on the
  -- initial prefix `⟨s, Seq.nil⟩`; halt everywhere else.
  let σ : WeakScheduler ls :=
    { next := fun e' =>
        if e'.init = s ∧ e'.trans = Seq.nil then PMF.pure (some (l, μ))
        else PMF.pure none
      valid := by
        intro e' n s' h_term h_state l' μ' h_supp
        by_cases h_cond : e'.init = s ∧ e'.trans = Seq.nil
        · simp only [if_pos h_cond, PMF.mem_support_pure_iff,
            Option.some.injEq, Prod.mk.injEq] at h_supp
          obtain ⟨h_l, h_μ⟩ := h_supp
          subst h_l; subst h_μ
          have h_init_eq : s' = s := by
            rcases Nat.eq_zero_or_pos n with hn | hn
            · subst hn
              have : e'.stateAt 0 = some e'.init := rfl
              rw [this, h_cond.1] at h_state
              exact (Option.some.inj h_state).symm
            · exfalso
              obtain ⟨k, hk⟩ := Nat.exists_eq_succ_of_ne_zero hn.ne'
              rw [hk] at h_state
              change (e'.trans.get? k).map Prod.snd = some s' at h_state
              rw [h_cond.2] at h_state
              simp at h_state
          rw [h_init_eq]; exact h_step
        · simp only [if_neg h_cond, PMF.mem_support_pure_iff] at h_supp
          exact absurd h_supp (by simp)
      internal_only := by
        intro e' l' μ' h_supp
        by_cases h_cond : e'.init = s ∧ e'.trans = Seq.nil
        · simp only [if_pos h_cond, PMF.mem_support_pure_iff,
            Option.some.injEq, Prod.mk.injEq] at h_supp
          rw [h_supp.1]; exact h_int
        · simp only [if_neg h_cond, PMF.mem_support_pure_iff] at h_supp
          exact absurd h_supp (by simp) }
  refine ⟨σ, 1, ?_⟩
  -- (PMF.pure s).bind (σ.run 1) = σ.run 1 s = σ.runFromState 1 ⟨s, nil⟩ s.
  rw [PMF.pure_bind]
  -- Unfold σ.run, σ.runFromState 1, σ.next ⟨s, nil⟩ = PMF.pure (some (l, μ)).
  change σ.runFromState 1 ⟨s, Seq.nil⟩ s = μ
  have h_next : σ.next ⟨s, Seq.nil⟩ = PMF.pure (some (l, μ)) := by
    change (if (⟨s, Seq.nil⟩ : AlterSeq State Label).init = s ∧
        (⟨s, Seq.nil⟩ : AlterSeq State Label).trans = Seq.nil
        then PMF.pure (some (l, μ)) else PMF.pure none) = PMF.pure (some (l, μ))
    rw [if_pos ⟨rfl, rfl⟩]
  change (σ.next ⟨s, Seq.nil⟩).bind _ = μ
  rw [h_next, PMF.pure_bind]
  -- The "some (l, μ)" branch: μ.bind (fun s' => σ.runFromState 0 ... s') = μ.bind PMF.pure = μ.
  -- `runFromState 0 _ s' = PMF.pure s'` by definition.
  change μ.bind (fun s' => PMF.pure s') = μ
  exact PMF.bind_pure μ

end PLTS
